// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package database

import (
	"context"
)

const getOwnApplication = `-- name: GetOwnApplication :one
SELECT
    id, opening_id, applicant_user_id, message, work_sample_url,
    work_sample_context, availability, availability_confirmed,
    proposed_contribution, status, submitted_at, created_at, updated_at
FROM applications
WHERE opening_id = $1
  AND applicant_user_id = $2
`

type GetOwnApplicationParams struct {
	OpeningID       string `db:"opening_id" json:"opening_id"`
	ApplicantUserID int64  `db:"applicant_user_id" json:"applicant_user_id"`
}

func (q *Queries) GetOwnApplication(ctx context.Context, arg GetOwnApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, getOwnApplication, arg.OpeningID, arg.ApplicantUserID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OpeningID,
		&i.ApplicantUserID,
		&i.Message,
		&i.WorkSampleUrl,
		&i.WorkSampleContext,
		&i.Availability,
		&i.AvailabilityConfirmed,
		&i.ProposedContribution,
		&i.Status,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const submitOwnApplication = `-- name: SubmitOwnApplication :one
UPDATE applications AS application SET
    status = 'submitted',
    submitted_at = now(),
    updated_at = now()
FROM project_openings AS opening
WHERE application.opening_id = $1
  AND application.applicant_user_id = $2
  AND application.status = 'draft'
  AND opening.id = application.opening_id
  AND opening.publication_status = 'published'
  AND opening.owner_user_id IS DISTINCT FROM application.applicant_user_id
RETURNING
    application.id, application.opening_id, application.applicant_user_id,
    application.message, application.work_sample_url,
    application.work_sample_context, application.availability,
    application.availability_confirmed, application.proposed_contribution,
    application.status, application.submitted_at, application.created_at,
    application.updated_at
`

type SubmitOwnApplicationParams struct {
	OpeningID       string `db:"opening_id" json:"opening_id"`
	ApplicantUserID int64  `db:"applicant_user_id" json:"applicant_user_id"`
}

func (q *Queries) SubmitOwnApplication(ctx context.Context, arg SubmitOwnApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, submitOwnApplication, arg.OpeningID, arg.ApplicantUserID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OpeningID,
		&i.ApplicantUserID,
		&i.Message,
		&i.WorkSampleUrl,
		&i.WorkSampleContext,
		&i.Availability,
		&i.AvailabilityConfirmed,
		&i.ProposedContribution,
		&i.Status,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertApplicationDraft = `-- name: UpsertApplicationDraft :one
INSERT INTO applications (
    id, opening_id, applicant_user_id, message, work_sample_url,
    work_sample_context, availability, availability_confirmed,
    proposed_contribution, status
)
SELECT
    $1, opening.id, $2, $3,
    $4, $5,
    $6, $7,
    $8, 'draft'
FROM project_openings AS opening
WHERE opening.id = $9
  AND opening.publication_status = 'published'
  AND opening.owner_user_id IS DISTINCT FROM $2
ON CONFLICT (opening_id, applicant_user_id) DO UPDATE SET
    message = EXCLUDED.message,
    work_sample_url = EXCLUDED.work_sample_url,
    work_sample_context = EXCLUDED.work_sample_context,
    availability = EXCLUDED.availability,
    availability_confirmed = EXCLUDED.availability_confirmed,
    proposed_contribution = EXCLUDED.proposed_contribution,
    updated_at = now()
WHERE applications.status = 'draft'
RETURNING
    id, opening_id, applicant_user_id, message, work_sample_url,
    work_sample_context, availability, availability_confirmed,
    proposed_contribution, status, submitted_at, created_at, updated_at
`

type UpsertApplicationDraftParams struct {
	ID                    string `db:"id" json:"id"`
	ApplicantUserID       int64  `db:"applicant_user_id" json:"applicant_user_id"`
	Message               string `db:"message" json:"message"`
	WorkSampleUrl         string `db:"work_sample_url" json:"work_sample_url"`
	WorkSampleContext     string `db:"work_sample_context" json:"work_sample_context"`
	Availability          string `db:"availability" json:"availability"`
	AvailabilityConfirmed bool   `db:"availability_confirmed" json:"availability_confirmed"`
	ProposedContribution  string `db:"proposed_contribution" json:"proposed_contribution"`
	OpeningID             string `db:"opening_id" json:"opening_id"`
}

func (q *Queries) UpsertApplicationDraft(ctx context.Context, arg UpsertApplicationDraftParams) (Application, error) {
	row := q.db.QueryRow(ctx, upsertApplicationDraft,
		arg.ID,
		arg.ApplicantUserID,
		arg.Message,
		arg.WorkSampleUrl,
		arg.WorkSampleContext,
		arg.Availability,
		arg.AvailabilityConfirmed,
		arg.ProposedContribution,
		arg.OpeningID,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OpeningID,
		&i.ApplicantUserID,
		&i.Message,
		&i.WorkSampleUrl,
		&i.WorkSampleContext,
		&i.Availability,
		&i.AvailabilityConfirmed,
		&i.ProposedContribution,
		&i.Status,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
