// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: applications.sql

package database

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOwnApplication = `-- name: GetOwnApplication :one
SELECT
    id, opening_id, applicant_user_id, message, work_sample_url,
    work_sample_context, availability, availability_confirmed,
    proposed_contribution, status, submitted_at, created_at, updated_at
FROM applications
WHERE opening_id = $1
  AND applicant_user_id = $2
`

type GetOwnApplicationParams struct {
	OpeningID       string `db:"opening_id" json:"opening_id"`
	ApplicantUserID int64  `db:"applicant_user_id" json:"applicant_user_id"`
}

func (q *Queries) GetOwnApplication(ctx context.Context, arg GetOwnApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, getOwnApplication, arg.OpeningID, arg.ApplicantUserID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OpeningID,
		&i.ApplicantUserID,
		&i.Message,
		&i.WorkSampleUrl,
		&i.WorkSampleContext,
		&i.Availability,
		&i.AvailabilityConfirmed,
		&i.ProposedContribution,
		&i.Status,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOwnedOpeningApplicationReviewScope = `-- name: GetOwnedOpeningApplicationReviewScope :one
SELECT id
FROM project_openings
WHERE id = $1
  AND owner_user_id = $2
`

type GetOwnedOpeningApplicationReviewScopeParams struct {
	OpeningID   string `db:"opening_id" json:"opening_id"`
	OwnerUserID *int64 `db:"owner_user_id" json:"owner_user_id"`
}

func (q *Queries) GetOwnedOpeningApplicationReviewScope(ctx context.Context, arg GetOwnedOpeningApplicationReviewScopeParams) (string, error) {
	row := q.db.QueryRow(ctx, getOwnedOpeningApplicationReviewScope, arg.OpeningID, arg.OwnerUserID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listSubmittedApplicationsForOwner = `-- name: ListSubmittedApplicationsForOwner :many
SELECT
    application.id, application.opening_id, application.applicant_user_id,
    application.message, application.work_sample_url,
    application.work_sample_context, application.availability,
    application.availability_confirmed, application.proposed_contribution,
    application.status, application.submitted_at, application.created_at,
    application.updated_at,
    profiles.display_name AS applicant_display_name,
    profiles.primary_role AS applicant_primary_role,
    profiles.skills AS applicant_skills,
    users.profile_url AS applicant_github_url,
    profiles.portfolio_url AS applicant_portfolio_url,
    profiles.evidence_summary AS applicant_evidence_summary
FROM applications AS application
JOIN project_openings AS opening ON opening.id = application.opening_id
JOIN profiles ON profiles.user_id = application.applicant_user_id
JOIN users ON users.id = application.applicant_user_id
WHERE application.opening_id = $1
  AND opening.owner_user_id = $2
  AND application.status = 'submitted'
ORDER BY application.submitted_at ASC, application.id ASC
`

type ListSubmittedApplicationsForOwnerParams struct {
	OpeningID   string `db:"opening_id" json:"opening_id"`
	OwnerUserID *int64 `db:"owner_user_id" json:"owner_user_id"`
}

type ListSubmittedApplicationsForOwnerRow struct {
	ID                       string             `db:"id" json:"id"`
	OpeningID                string             `db:"opening_id" json:"opening_id"`
	ApplicantUserID          int64              `db:"applicant_user_id" json:"applicant_user_id"`
	Message                  string             `db:"message" json:"message"`
	WorkSampleUrl            string             `db:"work_sample_url" json:"work_sample_url"`
	WorkSampleContext        string             `db:"work_sample_context" json:"work_sample_context"`
	Availability             string             `db:"availability" json:"availability"`
	AvailabilityConfirmed    bool               `db:"availability_confirmed" json:"availability_confirmed"`
	ProposedContribution     string             `db:"proposed_contribution" json:"proposed_contribution"`
	Status                   string             `db:"status" json:"status"`
	SubmittedAt              pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	CreatedAt                time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt                time.Time          `db:"updated_at" json:"updated_at"`
	ApplicantDisplayName     string             `db:"applicant_display_name" json:"applicant_display_name"`
	ApplicantPrimaryRole     string             `db:"applicant_primary_role" json:"applicant_primary_role"`
	ApplicantSkills          []string           `db:"applicant_skills" json:"applicant_skills"`
	ApplicantGithubUrl       string             `db:"applicant_github_url" json:"applicant_github_url"`
	ApplicantPortfolioUrl    *string            `db:"applicant_portfolio_url" json:"applicant_portfolio_url"`
	ApplicantEvidenceSummary string             `db:"applicant_evidence_summary" json:"applicant_evidence_summary"`
}

func (q *Queries) ListSubmittedApplicationsForOwner(ctx context.Context, arg ListSubmittedApplicationsForOwnerParams) ([]ListSubmittedApplicationsForOwnerRow, error) {
	rows, err := q.db.Query(ctx, listSubmittedApplicationsForOwner, arg.OpeningID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSubmittedApplicationsForOwnerRow{}
	for rows.Next() {
		var i ListSubmittedApplicationsForOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.OpeningID,
			&i.ApplicantUserID,
			&i.Message,
			&i.WorkSampleUrl,
			&i.WorkSampleContext,
			&i.Availability,
			&i.AvailabilityConfirmed,
			&i.ProposedContribution,
			&i.Status,
			&i.SubmittedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ApplicantDisplayName,
			&i.ApplicantPrimaryRole,
			&i.ApplicantSkills,
			&i.ApplicantGithubUrl,
			&i.ApplicantPortfolioUrl,
			&i.ApplicantEvidenceSummary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const submitOwnApplication = `-- name: SubmitOwnApplication :one
UPDATE applications AS application SET
    status = 'submitted',
    submitted_at = now(),
    updated_at = now()
FROM project_openings AS opening
WHERE application.opening_id = $1
  AND application.applicant_user_id = $2
  AND application.status = 'draft'
  AND opening.id = application.opening_id
  AND opening.publication_status = 'published'
  AND opening.owner_user_id IS DISTINCT FROM application.applicant_user_id
RETURNING
    application.id, application.opening_id, application.applicant_user_id,
    application.message, application.work_sample_url,
    application.work_sample_context, application.availability,
    application.availability_confirmed, application.proposed_contribution,
    application.status, application.submitted_at, application.created_at,
    application.updated_at
`

type SubmitOwnApplicationParams struct {
	OpeningID       string `db:"opening_id" json:"opening_id"`
	ApplicantUserID int64  `db:"applicant_user_id" json:"applicant_user_id"`
}

func (q *Queries) SubmitOwnApplication(ctx context.Context, arg SubmitOwnApplicationParams) (Application, error) {
	row := q.db.QueryRow(ctx, submitOwnApplication, arg.OpeningID, arg.ApplicantUserID)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OpeningID,
		&i.ApplicantUserID,
		&i.Message,
		&i.WorkSampleUrl,
		&i.WorkSampleContext,
		&i.Availability,
		&i.AvailabilityConfirmed,
		&i.ProposedContribution,
		&i.Status,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertApplicationDraft = `-- name: UpsertApplicationDraft :one
INSERT INTO applications (
    id, opening_id, applicant_user_id, message, work_sample_url,
    work_sample_context, availability, availability_confirmed,
    proposed_contribution, status
)
SELECT
    $1, opening.id, $2, $3,
    $4, $5,
    $6, $7,
    $8, 'draft'
FROM project_openings AS opening
WHERE opening.id = $9
  AND opening.publication_status = 'published'
  AND opening.owner_user_id IS DISTINCT FROM $2
ON CONFLICT (opening_id, applicant_user_id) DO UPDATE SET
    message = EXCLUDED.message,
    work_sample_url = EXCLUDED.work_sample_url,
    work_sample_context = EXCLUDED.work_sample_context,
    availability = EXCLUDED.availability,
    availability_confirmed = EXCLUDED.availability_confirmed,
    proposed_contribution = EXCLUDED.proposed_contribution,
    updated_at = now()
WHERE applications.status = 'draft'
RETURNING
    id, opening_id, applicant_user_id, message, work_sample_url,
    work_sample_context, availability, availability_confirmed,
    proposed_contribution, status, submitted_at, created_at, updated_at
`

type UpsertApplicationDraftParams struct {
	ID                    string `db:"id" json:"id"`
	ApplicantUserID       int64  `db:"applicant_user_id" json:"applicant_user_id"`
	Message               string `db:"message" json:"message"`
	WorkSampleUrl         string `db:"work_sample_url" json:"work_sample_url"`
	WorkSampleContext     string `db:"work_sample_context" json:"work_sample_context"`
	Availability          string `db:"availability" json:"availability"`
	AvailabilityConfirmed bool   `db:"availability_confirmed" json:"availability_confirmed"`
	ProposedContribution  string `db:"proposed_contribution" json:"proposed_contribution"`
	OpeningID             string `db:"opening_id" json:"opening_id"`
}

func (q *Queries) UpsertApplicationDraft(ctx context.Context, arg UpsertApplicationDraftParams) (Application, error) {
	row := q.db.QueryRow(ctx, upsertApplicationDraft,
		arg.ID,
		arg.ApplicantUserID,
		arg.Message,
		arg.WorkSampleUrl,
		arg.WorkSampleContext,
		arg.Availability,
		arg.AvailabilityConfirmed,
		arg.ProposedContribution,
		arg.OpeningID,
	)
	var i Application
	err := row.Scan(
		&i.ID,
		&i.OpeningID,
		&i.ApplicantUserID,
		&i.Message,
		&i.WorkSampleUrl,
		&i.WorkSampleContext,
		&i.Availability,
		&i.AvailabilityConfirmed,
		&i.ProposedContribution,
		&i.Status,
		&i.SubmittedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
