// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package database

import (
	"context"
	"time"
)

const consumeOAuthAttempt = `-- name: ConsumeOAuthAttempt :one
DELETE FROM oauth_attempts
WHERE state_hash = $1 AND expires_at > now()
RETURNING code_verifier
`

func (q *Queries) ConsumeOAuthAttempt(ctx context.Context, stateHash []byte) (string, error) {
	row := q.db.QueryRow(ctx, consumeOAuthAttempt, stateHash)
	var code_verifier string
	err := row.Scan(&code_verifier)
	return code_verifier, err
}

const createOAuthAttempt = `-- name: CreateOAuthAttempt :exec
INSERT INTO oauth_attempts (state_hash, code_verifier, expires_at)
VALUES ($1, $2, $3)
`

type CreateOAuthAttemptParams struct {
	StateHash    []byte    `db:"state_hash" json:"state_hash"`
	CodeVerifier string    `db:"code_verifier" json:"code_verifier"`
	ExpiresAt    time.Time `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateOAuthAttempt(ctx context.Context, arg CreateOAuthAttemptParams) error {
	_, err := q.db.Exec(ctx, createOAuthAttempt, arg.StateHash, arg.CodeVerifier, arg.ExpiresAt)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO sessions (token_hash, user_id, expires_at)
VALUES ($1, $2, $3)
`

type CreateSessionParams struct {
	TokenHash []byte    `db:"token_hash" json:"token_hash"`
	UserID    int64     `db:"user_id" json:"user_id"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const deleteExpiredOAuthAttempts = `-- name: DeleteExpiredOAuthAttempts :exec
DELETE FROM oauth_attempts WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredOAuthAttempts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredOAuthAttempts)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM sessions WHERE expires_at <= now()
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSession(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, deleteSession, tokenHash)
	return err
}

const getSessionUser = `-- name: GetSessionUser :one
SELECT
    users.id,
    users.github_user_id,
    users.github_login,
    users.display_name,
    users.avatar_url,
    users.profile_url,
    users.account_role
FROM sessions
JOIN users ON users.id = sessions.user_id
WHERE sessions.token_hash = $1
  AND sessions.expires_at > now()
`

type GetSessionUserRow struct {
	ID           int64   `db:"id" json:"id"`
	GithubUserID int64   `db:"github_user_id" json:"github_user_id"`
	GithubLogin  string  `db:"github_login" json:"github_login"`
	DisplayName  *string `db:"display_name" json:"display_name"`
	AvatarUrl    string  `db:"avatar_url" json:"avatar_url"`
	ProfileUrl   string  `db:"profile_url" json:"profile_url"`
	AccountRole  string  `db:"account_role" json:"account_role"`
}

func (q *Queries) GetSessionUser(ctx context.Context, tokenHash []byte) (GetSessionUserRow, error) {
	row := q.db.QueryRow(ctx, getSessionUser, tokenHash)
	var i GetSessionUserRow
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.GithubLogin,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.ProfileUrl,
		&i.AccountRole,
	)
	return i, err
}

const upsertGitHubUser = `-- name: UpsertGitHubUser :one
INSERT INTO users (
    github_user_id,
    github_login,
    display_name,
    avatar_url,
    profile_url
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (github_user_id) DO UPDATE SET
    github_login = EXCLUDED.github_login,
    display_name = EXCLUDED.display_name,
    avatar_url = EXCLUDED.avatar_url,
    profile_url = EXCLUDED.profile_url,
    updated_at = now()
RETURNING id, github_user_id, github_login, display_name, avatar_url, profile_url, account_role
`

type UpsertGitHubUserParams struct {
	GithubUserID int64   `db:"github_user_id" json:"github_user_id"`
	GithubLogin  string  `db:"github_login" json:"github_login"`
	DisplayName  *string `db:"display_name" json:"display_name"`
	AvatarUrl    string  `db:"avatar_url" json:"avatar_url"`
	ProfileUrl   string  `db:"profile_url" json:"profile_url"`
}

type UpsertGitHubUserRow struct {
	ID           int64   `db:"id" json:"id"`
	GithubUserID int64   `db:"github_user_id" json:"github_user_id"`
	GithubLogin  string  `db:"github_login" json:"github_login"`
	DisplayName  *string `db:"display_name" json:"display_name"`
	AvatarUrl    string  `db:"avatar_url" json:"avatar_url"`
	ProfileUrl   string  `db:"profile_url" json:"profile_url"`
	AccountRole  string  `db:"account_role" json:"account_role"`
}

func (q *Queries) UpsertGitHubUser(ctx context.Context, arg UpsertGitHubUserParams) (UpsertGitHubUserRow, error) {
	row := q.db.QueryRow(ctx, upsertGitHubUser,
		arg.GithubUserID,
		arg.GithubLogin,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.ProfileUrl,
	)
	var i UpsertGitHubUserRow
	err := row.Scan(
		&i.ID,
		&i.GithubUserID,
		&i.GithubLogin,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.ProfileUrl,
		&i.AccountRole,
	)
	return i, err
}
