// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: moderation_appeals.sql

package database

import (
	"context"
	"time"
)

const createTrialFeedbackModerationAppeal = `-- name: CreateTrialFeedbackModerationAppeal :one
WITH eligible_report AS (
    SELECT report.id
    FROM safety_reports AS report
    JOIN trial_feedback AS feedback ON feedback.id = report.target_id
    WHERE report.target_kind = 'trial_feedback'
      AND report.report_status = 'upheld'
      AND report.target_id = $1
      AND feedback.author_user_id = $2
      AND report.reporter_user_id <> $2
    ORDER BY report.decided_at ASC, report.id ASC
    LIMIT 1
), inserted AS (
    INSERT INTO moderation_appeals (id, report_id, appellant_user_id, reason)
    SELECT $3, eligible_report.id, $2, $4
    FROM eligible_report
    ON CONFLICT (report_id) DO NOTHING
    RETURNING id, report_id, appellant_user_id, reason, appeal_status, created_at
)
SELECT inserted.id, inserted.report_id, inserted.appellant_user_id, inserted.reason, inserted.appeal_status, inserted.created_at, report.target_kind, report.target_id, appellant.github_login AS appellant_github_login
FROM inserted
JOIN safety_reports AS report ON report.id = inserted.report_id
JOIN users AS appellant ON appellant.id = inserted.appellant_user_id
`

type CreateTrialFeedbackModerationAppealParams struct {
	TargetID        string `db:"target_id" json:"target_id"`
	AppellantUserID int64  `db:"appellant_user_id" json:"appellant_user_id"`
	ID              string `db:"id" json:"id"`
	Reason          string `db:"reason" json:"reason"`
}

type CreateTrialFeedbackModerationAppealRow struct {
	ID                   string    `db:"id" json:"id"`
	ReportID             string    `db:"report_id" json:"report_id"`
	AppellantUserID      int64     `db:"appellant_user_id" json:"appellant_user_id"`
	Reason               string    `db:"reason" json:"reason"`
	AppealStatus         string    `db:"appeal_status" json:"appeal_status"`
	CreatedAt            time.Time `db:"created_at" json:"created_at"`
	TargetKind           string    `db:"target_kind" json:"target_kind"`
	TargetID             string    `db:"target_id" json:"target_id"`
	AppellantGithubLogin string    `db:"appellant_github_login" json:"appellant_github_login"`
}

func (q *Queries) CreateTrialFeedbackModerationAppeal(ctx context.Context, arg CreateTrialFeedbackModerationAppealParams) (CreateTrialFeedbackModerationAppealRow, error) {
	row := q.db.QueryRow(ctx, createTrialFeedbackModerationAppeal,
		arg.TargetID,
		arg.AppellantUserID,
		arg.ID,
		arg.Reason,
	)
	var i CreateTrialFeedbackModerationAppealRow
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.AppellantUserID,
		&i.Reason,
		&i.AppealStatus,
		&i.CreatedAt,
		&i.TargetKind,
		&i.TargetID,
		&i.AppellantGithubLogin,
	)
	return i, err
}

const createTrustCandidateModerationAppeal = `-- name: CreateTrustCandidateModerationAppeal :one
WITH eligible_report AS (
    SELECT report.id
    FROM safety_reports AS report
    JOIN trial_proposals AS proposal ON proposal.id = report.target_id
    JOIN project_openings AS opening ON opening.id = proposal.opening_id
    WHERE report.target_kind = 'trust_candidate'
      AND report.report_status = 'upheld'
      AND report.target_id = $1
      AND report.reporter_user_id <> $2
      AND (
          proposal.applicant_user_id = $2
          OR opening.owner_user_id = $2
      )
    ORDER BY report.decided_at ASC, report.id ASC
    LIMIT 1
), inserted AS (
    INSERT INTO moderation_appeals (id, report_id, appellant_user_id, reason)
    SELECT $3, eligible_report.id, $2, $4
    FROM eligible_report
    ON CONFLICT (report_id) DO NOTHING
    RETURNING id, report_id, appellant_user_id, reason, appeal_status, created_at
)
SELECT inserted.id, inserted.report_id, inserted.appellant_user_id, inserted.reason, inserted.appeal_status, inserted.created_at, report.target_kind, report.target_id, appellant.github_login AS appellant_github_login
FROM inserted
JOIN safety_reports AS report ON report.id = inserted.report_id
JOIN users AS appellant ON appellant.id = inserted.appellant_user_id
`

type CreateTrustCandidateModerationAppealParams struct {
	TargetID        string `db:"target_id" json:"target_id"`
	AppellantUserID int64  `db:"appellant_user_id" json:"appellant_user_id"`
	ID              string `db:"id" json:"id"`
	Reason          string `db:"reason" json:"reason"`
}

type CreateTrustCandidateModerationAppealRow struct {
	ID                   string    `db:"id" json:"id"`
	ReportID             string    `db:"report_id" json:"report_id"`
	AppellantUserID      int64     `db:"appellant_user_id" json:"appellant_user_id"`
	Reason               string    `db:"reason" json:"reason"`
	AppealStatus         string    `db:"appeal_status" json:"appeal_status"`
	CreatedAt            time.Time `db:"created_at" json:"created_at"`
	TargetKind           string    `db:"target_kind" json:"target_kind"`
	TargetID             string    `db:"target_id" json:"target_id"`
	AppellantGithubLogin string    `db:"appellant_github_login" json:"appellant_github_login"`
}

func (q *Queries) CreateTrustCandidateModerationAppeal(ctx context.Context, arg CreateTrustCandidateModerationAppealParams) (CreateTrustCandidateModerationAppealRow, error) {
	row := q.db.QueryRow(ctx, createTrustCandidateModerationAppeal,
		arg.TargetID,
		arg.AppellantUserID,
		arg.ID,
		arg.Reason,
	)
	var i CreateTrustCandidateModerationAppealRow
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.AppellantUserID,
		&i.Reason,
		&i.AppealStatus,
		&i.CreatedAt,
		&i.TargetKind,
		&i.TargetID,
		&i.AppellantGithubLogin,
	)
	return i, err
}

const listModerationAppealsForModerator = `-- name: ListModerationAppealsForModerator :many
SELECT appeal.id, appeal.report_id, appeal.appellant_user_id, appeal.reason, appeal.appeal_status, appeal.created_at, report.target_kind, report.target_id, appellant.github_login AS appellant_github_login
FROM moderation_appeals AS appeal
JOIN safety_reports AS report ON report.id = appeal.report_id
JOIN users AS appellant ON appellant.id = appeal.appellant_user_id
WHERE EXISTS (
    SELECT 1 FROM users AS moderator
    WHERE moderator.id = $1
      AND moderator.account_role = 'moderator'
)
ORDER BY appeal.created_at ASC, appeal.id ASC
`

type ListModerationAppealsForModeratorRow struct {
	ID                   string    `db:"id" json:"id"`
	ReportID             string    `db:"report_id" json:"report_id"`
	AppellantUserID      int64     `db:"appellant_user_id" json:"appellant_user_id"`
	Reason               string    `db:"reason" json:"reason"`
	AppealStatus         string    `db:"appeal_status" json:"appeal_status"`
	CreatedAt            time.Time `db:"created_at" json:"created_at"`
	TargetKind           string    `db:"target_kind" json:"target_kind"`
	TargetID             string    `db:"target_id" json:"target_id"`
	AppellantGithubLogin string    `db:"appellant_github_login" json:"appellant_github_login"`
}

func (q *Queries) ListModerationAppealsForModerator(ctx context.Context, moderatorUserID int64) ([]ListModerationAppealsForModeratorRow, error) {
	rows, err := q.db.Query(ctx, listModerationAppealsForModerator, moderatorUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListModerationAppealsForModeratorRow{}
	for rows.Next() {
		var i ListModerationAppealsForModeratorRow
		if err := rows.Scan(
			&i.ID,
			&i.ReportID,
			&i.AppellantUserID,
			&i.Reason,
			&i.AppealStatus,
			&i.CreatedAt,
			&i.TargetKind,
			&i.TargetID,
			&i.AppellantGithubLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
