// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type Application struct {
	ID                    string             `db:"id" json:"id"`
	OpeningID             string             `db:"opening_id" json:"opening_id"`
	ApplicantUserID       int64              `db:"applicant_user_id" json:"applicant_user_id"`
	Message               string             `db:"message" json:"message"`
	WorkSampleUrl         string             `db:"work_sample_url" json:"work_sample_url"`
	WorkSampleContext     string             `db:"work_sample_context" json:"work_sample_context"`
	Availability          string             `db:"availability" json:"availability"`
	AvailabilityConfirmed bool               `db:"availability_confirmed" json:"availability_confirmed"`
	ProposedContribution  string             `db:"proposed_contribution" json:"proposed_contribution"`
	Status                string             `db:"status" json:"status"`
	SubmittedAt           pgtype.Timestamptz `db:"submitted_at" json:"submitted_at"`
	CreatedAt             time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt             time.Time          `db:"updated_at" json:"updated_at"`
	DecidedAt             pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	WithdrawnAt           pgtype.Timestamptz `db:"withdrawn_at" json:"withdrawn_at"`
}

type ModerationAppeal struct {
	ID              string    `db:"id" json:"id"`
	ReportID        string    `db:"report_id" json:"report_id"`
	AppellantUserID int64     `db:"appellant_user_id" json:"appellant_user_id"`
	Reason          string    `db:"reason" json:"reason"`
	AppealStatus    string    `db:"appeal_status" json:"appeal_status"`
	CreatedAt       time.Time `db:"created_at" json:"created_at"`
}

type OauthAttempt struct {
	StateHash    []byte    `db:"state_hash" json:"state_hash"`
	CodeVerifier string    `db:"code_verifier" json:"code_verifier"`
	ExpiresAt    time.Time `db:"expires_at" json:"expires_at"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
}

type Profile struct {
	UserID               int64     `db:"user_id" json:"user_id"`
	DisplayName          string    `db:"display_name" json:"display_name"`
	PrimaryRole          string    `db:"primary_role" json:"primary_role"`
	Bio                  string    `db:"bio" json:"bio"`
	Timezone             string    `db:"timezone" json:"timezone"`
	WeeklyAvailability   string    `db:"weekly_availability" json:"weekly_availability"`
	PreferredDuration    string    `db:"preferred_duration" json:"preferred_duration"`
	WorkStyle            string    `db:"work_style" json:"work_style"`
	CommunicationCadence string    `db:"communication_cadence" json:"communication_cadence"`
	Skills               []string  `db:"skills" json:"skills"`
	PortfolioUrl         *string   `db:"portfolio_url" json:"portfolio_url"`
	EvidenceSummary      string    `db:"evidence_summary" json:"evidence_summary"`
	CreatedAt            time.Time `db:"created_at" json:"created_at"`
	UpdatedAt            time.Time `db:"updated_at" json:"updated_at"`
}

type ProjectOpening struct {
	ID                string             `db:"id" json:"id"`
	Title             string             `db:"title" json:"title"`
	Summary           string             `db:"summary" json:"summary"`
	Skills            []string           `db:"skills" json:"skills"`
	Role              string             `db:"role" json:"role"`
	Compensation      string             `db:"compensation" json:"compensation"`
	Commitment        string             `db:"commitment" json:"commitment"`
	CommitmentBand    string             `db:"commitment_band" json:"commitment_band"`
	Duration          string             `db:"duration" json:"duration"`
	Timezone          string             `db:"timezone" json:"timezone"`
	Freshness         string             `db:"freshness" json:"freshness"`
	Stage             string             `db:"stage" json:"stage"`
	DesiredOutcome    string             `db:"desired_outcome" json:"desired_outcome"`
	FirstMilestone    string             `db:"first_milestone" json:"first_milestone"`
	OwnerContribution string             `db:"owner_contribution" json:"owner_contribution"`
	OwnerName         string             `db:"owner_name" json:"owner_name"`
	OwnerSignal       string             `db:"owner_signal" json:"owner_signal"`
	Confidentiality   string             `db:"confidentiality" json:"confidentiality"`
	DisplayOrder      int32              `db:"display_order" json:"display_order"`
	CreatedAt         time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt         time.Time          `db:"updated_at" json:"updated_at"`
	OwnerUserID       *int64             `db:"owner_user_id" json:"owner_user_id"`
	PublicationStatus string             `db:"publication_status" json:"publication_status"`
	PublishedAt       pgtype.Timestamptz `db:"published_at" json:"published_at"`
	ClosedAt          pgtype.Timestamptz `db:"closed_at" json:"closed_at"`
}

type SafetyReport struct {
	ID               string             `db:"id" json:"id"`
	ReporterUserID   int64              `db:"reporter_user_id" json:"reporter_user_id"`
	TargetKind       string             `db:"target_kind" json:"target_kind"`
	TargetID         string             `db:"target_id" json:"target_id"`
	Category         string             `db:"category" json:"category"`
	Details          string             `db:"details" json:"details"`
	TargetSnapshot   []byte             `db:"target_snapshot" json:"target_snapshot"`
	ReportStatus     string             `db:"report_status" json:"report_status"`
	ReviewedByUserID *int64             `db:"reviewed_by_user_id" json:"reviewed_by_user_id"`
	ModeratorNotes   *string            `db:"moderator_notes" json:"moderator_notes"`
	CreatedAt        time.Time          `db:"created_at" json:"created_at"`
	DecidedAt        pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
}

type Session struct {
	TokenHash []byte    `db:"token_hash" json:"token_hash"`
	UserID    int64     `db:"user_id" json:"user_id"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type TrialCheckIn struct {
	ID           string    `db:"id" json:"id"`
	ProposalID   string    `db:"proposal_id" json:"proposal_id"`
	AuthorUserID int64     `db:"author_user_id" json:"author_user_id"`
	CheckInKind  string    `db:"check_in_kind" json:"check_in_kind"`
	UpdateText   string    `db:"update_text" json:"update_text"`
	EvidenceUrl  string    `db:"evidence_url" json:"evidence_url"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
}

type TrialFeedback struct {
	ID                   string             `db:"id" json:"id"`
	ProposalID           string             `db:"proposal_id" json:"proposal_id"`
	AuthorUserID         int64              `db:"author_user_id" json:"author_user_id"`
	ObservedBehaviors    []string           `db:"observed_behaviors" json:"observed_behaviors"`
	CollaborationExample string             `db:"collaboration_example" json:"collaboration_example"`
	CollaborateAgain     string             `db:"collaborate_again" json:"collaborate_again"`
	ReviewSummary        string             `db:"review_summary" json:"review_summary"`
	AcknowledgedByUserID *int64             `db:"acknowledged_by_user_id" json:"acknowledged_by_user_id"`
	SubmittedAt          time.Time          `db:"submitted_at" json:"submitted_at"`
	AcknowledgedAt       pgtype.Timestamptz `db:"acknowledged_at" json:"acknowledged_at"`
}

type TrialOutcome struct {
	ID                string             `db:"id" json:"id"`
	ProposalID        string             `db:"proposal_id" json:"proposal_id"`
	SubmittedByUserID int64              `db:"submitted_by_user_id" json:"submitted_by_user_id"`
	OutcomeStatus     string             `db:"outcome_status" json:"outcome_status"`
	DeliverableStatus string             `db:"deliverable_status" json:"deliverable_status"`
	WorkSummary       string             `db:"work_summary" json:"work_summary"`
	EvidenceUrl       string             `db:"evidence_url" json:"evidence_url"`
	CloseoutNotes     string             `db:"closeout_notes" json:"closeout_notes"`
	ReviewStatus      string             `db:"review_status" json:"review_status"`
	DecidedByUserID   *int64             `db:"decided_by_user_id" json:"decided_by_user_id"`
	SubmittedAt       time.Time          `db:"submitted_at" json:"submitted_at"`
	DecidedAt         pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
}

type TrialProposal struct {
	ID              string             `db:"id" json:"id"`
	ApplicationID   string             `db:"application_id" json:"application_id"`
	OpeningID       string             `db:"opening_id" json:"opening_id"`
	ApplicantUserID int64              `db:"applicant_user_id" json:"applicant_user_id"`
	Outcome         string             `db:"outcome" json:"outcome"`
	Deliverable     string             `db:"deliverable" json:"deliverable"`
	NonGoals        string             `db:"non_goals" json:"non_goals"`
	StartDate       pgtype.Date        `db:"start_date" json:"start_date"`
	EndDate         pgtype.Date        `db:"end_date" json:"end_date"`
	WeeklyHours     int32              `db:"weekly_hours" json:"weekly_hours"`
	CheckInCadence  string             `db:"check_in_cadence" json:"check_in_cadence"`
	AccessLevel     string             `db:"access_level" json:"access_level"`
	Confidentiality string             `db:"confidentiality" json:"confidentiality"`
	IpOwnership     string             `db:"ip_ownership" json:"ip_ownership"`
	ExitPlan        string             `db:"exit_plan" json:"exit_plan"`
	TermsConfirmed  bool               `db:"terms_confirmed" json:"terms_confirmed"`
	ProposalStatus  string             `db:"proposal_status" json:"proposal_status"`
	CreatedAt       time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt       time.Time          `db:"updated_at" json:"updated_at"`
	SentAt          pgtype.Timestamptz `db:"sent_at" json:"sent_at"`
	DecidedAt       pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
}

type User struct {
	ID           int64     `db:"id" json:"id"`
	GithubUserID int64     `db:"github_user_id" json:"github_user_id"`
	GithubLogin  string    `db:"github_login" json:"github_login"`
	DisplayName  *string   `db:"display_name" json:"display_name"`
	AvatarUrl    string    `db:"avatar_url" json:"avatar_url"`
	ProfileUrl   string    `db:"profile_url" json:"profile_url"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time `db:"updated_at" json:"updated_at"`
	AccountRole  string    `db:"account_role" json:"account_role"`
}
