// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"time"
)

type OauthAttempt struct {
	StateHash    []byte    `db:"state_hash" json:"state_hash"`
	CodeVerifier string    `db:"code_verifier" json:"code_verifier"`
	ExpiresAt    time.Time `db:"expires_at" json:"expires_at"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
}

type Profile struct {
	UserID               int64     `db:"user_id" json:"user_id"`
	DisplayName          string    `db:"display_name" json:"display_name"`
	PrimaryRole          string    `db:"primary_role" json:"primary_role"`
	Bio                  string    `db:"bio" json:"bio"`
	Timezone             string    `db:"timezone" json:"timezone"`
	WeeklyAvailability   string    `db:"weekly_availability" json:"weekly_availability"`
	PreferredDuration    string    `db:"preferred_duration" json:"preferred_duration"`
	WorkStyle            string    `db:"work_style" json:"work_style"`
	CommunicationCadence string    `db:"communication_cadence" json:"communication_cadence"`
	Skills               []string  `db:"skills" json:"skills"`
	PortfolioUrl         *string   `db:"portfolio_url" json:"portfolio_url"`
	EvidenceSummary      string    `db:"evidence_summary" json:"evidence_summary"`
	CreatedAt            time.Time `db:"created_at" json:"created_at"`
	UpdatedAt            time.Time `db:"updated_at" json:"updated_at"`
}

type ProjectOpening struct {
	ID                string    `db:"id" json:"id"`
	Title             string    `db:"title" json:"title"`
	Summary           string    `db:"summary" json:"summary"`
	Skills            []string  `db:"skills" json:"skills"`
	Role              string    `db:"role" json:"role"`
	Compensation      string    `db:"compensation" json:"compensation"`
	Commitment        string    `db:"commitment" json:"commitment"`
	CommitmentBand    string    `db:"commitment_band" json:"commitment_band"`
	Duration          string    `db:"duration" json:"duration"`
	Timezone          string    `db:"timezone" json:"timezone"`
	Freshness         string    `db:"freshness" json:"freshness"`
	Stage             string    `db:"stage" json:"stage"`
	DesiredOutcome    string    `db:"desired_outcome" json:"desired_outcome"`
	FirstMilestone    string    `db:"first_milestone" json:"first_milestone"`
	OwnerContribution string    `db:"owner_contribution" json:"owner_contribution"`
	OwnerName         string    `db:"owner_name" json:"owner_name"`
	OwnerSignal       string    `db:"owner_signal" json:"owner_signal"`
	Confidentiality   string    `db:"confidentiality" json:"confidentiality"`
	DisplayOrder      int32     `db:"display_order" json:"display_order"`
	CreatedAt         time.Time `db:"created_at" json:"created_at"`
	UpdatedAt         time.Time `db:"updated_at" json:"updated_at"`
}

type Session struct {
	TokenHash []byte    `db:"token_hash" json:"token_hash"`
	UserID    int64     `db:"user_id" json:"user_id"`
	ExpiresAt time.Time `db:"expires_at" json:"expires_at"`
	CreatedAt time.Time `db:"created_at" json:"created_at"`
}

type User struct {
	ID           int64     `db:"id" json:"id"`
	GithubUserID int64     `db:"github_user_id" json:"github_user_id"`
	GithubLogin  string    `db:"github_login" json:"github_login"`
	DisplayName  *string   `db:"display_name" json:"display_name"`
	AvatarUrl    string    `db:"avatar_url" json:"avatar_url"`
	ProfileUrl   string    `db:"profile_url" json:"profile_url"`
	CreatedAt    time.Time `db:"created_at" json:"created_at"`
	UpdatedAt    time.Time `db:"updated_at" json:"updated_at"`
}
