// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: openings.sql

package database

import (
	"context"
)

const listOpenings = `-- name: ListOpenings :many
SELECT
    id,
    title,
    summary,
    skills,
    role,
    compensation,
    commitment,
    commitment_band,
    duration,
    timezone,
    freshness,
    stage,
    desired_outcome,
    first_milestone,
    owner_contribution,
    owner_name,
    owner_signal,
    confidentiality
FROM project_openings
WHERE
    ($1::text = '' OR role = $1::text)
    AND ($2::text = '' OR compensation = $2::text)
    AND ($3::text = '' OR commitment_band = $3::text)
    AND (
        trim($4::text) = ''
        OR to_tsvector(
            'simple',
            concat_ws(
                ' ',
                title,
                summary,
                array_to_string(skills, ' '),
                role,
                compensation,
                commitment,
                duration,
                timezone,
                stage
            )
        ) @@ plainto_tsquery('simple', $4::text)
    )
ORDER BY display_order, id
`

type ListOpeningsParams struct {
	Role         string `db:"role" json:"role"`
	Compensation string `db:"compensation" json:"compensation"`
	Commitment   string `db:"commitment" json:"commitment"`
	Query        string `db:"query" json:"query"`
}

type ListOpeningsRow struct {
	ID                string   `db:"id" json:"id"`
	Title             string   `db:"title" json:"title"`
	Summary           string   `db:"summary" json:"summary"`
	Skills            []string `db:"skills" json:"skills"`
	Role              string   `db:"role" json:"role"`
	Compensation      string   `db:"compensation" json:"compensation"`
	Commitment        string   `db:"commitment" json:"commitment"`
	CommitmentBand    string   `db:"commitment_band" json:"commitment_band"`
	Duration          string   `db:"duration" json:"duration"`
	Timezone          string   `db:"timezone" json:"timezone"`
	Freshness         string   `db:"freshness" json:"freshness"`
	Stage             string   `db:"stage" json:"stage"`
	DesiredOutcome    string   `db:"desired_outcome" json:"desired_outcome"`
	FirstMilestone    string   `db:"first_milestone" json:"first_milestone"`
	OwnerContribution string   `db:"owner_contribution" json:"owner_contribution"`
	OwnerName         string   `db:"owner_name" json:"owner_name"`
	OwnerSignal       string   `db:"owner_signal" json:"owner_signal"`
	Confidentiality   string   `db:"confidentiality" json:"confidentiality"`
}

func (q *Queries) ListOpenings(ctx context.Context, arg ListOpeningsParams) ([]ListOpeningsRow, error) {
	rows, err := q.db.Query(ctx, listOpenings,
		arg.Role,
		arg.Compensation,
		arg.Commitment,
		arg.Query,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpeningsRow{}
	for rows.Next() {
		var i ListOpeningsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Summary,
			&i.Skills,
			&i.Role,
			&i.Compensation,
			&i.Commitment,
			&i.CommitmentBand,
			&i.Duration,
			&i.Timezone,
			&i.Freshness,
			&i.Stage,
			&i.DesiredOutcome,
			&i.FirstMilestone,
			&i.OwnerContribution,
			&i.OwnerName,
			&i.OwnerSignal,
			&i.Confidentiality,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
