// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package database

import (
	"context"
	"time"
)

const getProfile = `-- name: GetProfile :one
SELECT
    profiles.user_id,
    profiles.display_name,
    profiles.primary_role,
    profiles.bio,
    profiles.timezone,
    profiles.weekly_availability,
    profiles.preferred_duration,
    profiles.work_style,
    profiles.communication_cadence,
    profiles.skills,
    profiles.portfolio_url,
    profiles.evidence_summary,
    users.profile_url AS github_url,
    profiles.created_at,
    profiles.updated_at
FROM profiles
JOIN users ON users.id = profiles.user_id
WHERE profiles.user_id = $1
`

type GetProfileRow struct {
	UserID               int64     `db:"user_id" json:"user_id"`
	DisplayName          string    `db:"display_name" json:"display_name"`
	PrimaryRole          string    `db:"primary_role" json:"primary_role"`
	Bio                  string    `db:"bio" json:"bio"`
	Timezone             string    `db:"timezone" json:"timezone"`
	WeeklyAvailability   string    `db:"weekly_availability" json:"weekly_availability"`
	PreferredDuration    string    `db:"preferred_duration" json:"preferred_duration"`
	WorkStyle            string    `db:"work_style" json:"work_style"`
	CommunicationCadence string    `db:"communication_cadence" json:"communication_cadence"`
	Skills               []string  `db:"skills" json:"skills"`
	PortfolioUrl         *string   `db:"portfolio_url" json:"portfolio_url"`
	EvidenceSummary      string    `db:"evidence_summary" json:"evidence_summary"`
	GithubUrl            string    `db:"github_url" json:"github_url"`
	CreatedAt            time.Time `db:"created_at" json:"created_at"`
	UpdatedAt            time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetProfile(ctx context.Context, userID int64) (GetProfileRow, error) {
	row := q.db.QueryRow(ctx, getProfile, userID)
	var i GetProfileRow
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.PrimaryRole,
		&i.Bio,
		&i.Timezone,
		&i.WeeklyAvailability,
		&i.PreferredDuration,
		&i.WorkStyle,
		&i.CommunicationCadence,
		&i.Skills,
		&i.PortfolioUrl,
		&i.EvidenceSummary,
		&i.GithubUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertProfile = `-- name: UpsertProfile :one
INSERT INTO profiles (
    user_id,
    display_name,
    primary_role,
    bio,
    timezone,
    weekly_availability,
    preferred_duration,
    work_style,
    communication_cadence,
    skills,
    portfolio_url,
    evidence_summary
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12
)
ON CONFLICT (user_id) DO UPDATE SET
    display_name = EXCLUDED.display_name,
    primary_role = EXCLUDED.primary_role,
    bio = EXCLUDED.bio,
    timezone = EXCLUDED.timezone,
    weekly_availability = EXCLUDED.weekly_availability,
    preferred_duration = EXCLUDED.preferred_duration,
    work_style = EXCLUDED.work_style,
    communication_cadence = EXCLUDED.communication_cadence,
    skills = EXCLUDED.skills,
    portfolio_url = EXCLUDED.portfolio_url,
    evidence_summary = EXCLUDED.evidence_summary,
    updated_at = now()
RETURNING
    user_id,
    display_name,
    primary_role,
    bio,
    timezone,
    weekly_availability,
    preferred_duration,
    work_style,
    communication_cadence,
    skills,
    portfolio_url,
    evidence_summary,
    (SELECT profile_url FROM users WHERE id = profiles.user_id) AS github_url,
    created_at,
    updated_at
`

type UpsertProfileParams struct {
	UserID               int64    `db:"user_id" json:"user_id"`
	DisplayName          string   `db:"display_name" json:"display_name"`
	PrimaryRole          string   `db:"primary_role" json:"primary_role"`
	Bio                  string   `db:"bio" json:"bio"`
	Timezone             string   `db:"timezone" json:"timezone"`
	WeeklyAvailability   string   `db:"weekly_availability" json:"weekly_availability"`
	PreferredDuration    string   `db:"preferred_duration" json:"preferred_duration"`
	WorkStyle            string   `db:"work_style" json:"work_style"`
	CommunicationCadence string   `db:"communication_cadence" json:"communication_cadence"`
	Skills               []string `db:"skills" json:"skills"`
	PortfolioUrl         *string  `db:"portfolio_url" json:"portfolio_url"`
	EvidenceSummary      string   `db:"evidence_summary" json:"evidence_summary"`
}

type UpsertProfileRow struct {
	UserID               int64     `db:"user_id" json:"user_id"`
	DisplayName          string    `db:"display_name" json:"display_name"`
	PrimaryRole          string    `db:"primary_role" json:"primary_role"`
	Bio                  string    `db:"bio" json:"bio"`
	Timezone             string    `db:"timezone" json:"timezone"`
	WeeklyAvailability   string    `db:"weekly_availability" json:"weekly_availability"`
	PreferredDuration    string    `db:"preferred_duration" json:"preferred_duration"`
	WorkStyle            string    `db:"work_style" json:"work_style"`
	CommunicationCadence string    `db:"communication_cadence" json:"communication_cadence"`
	Skills               []string  `db:"skills" json:"skills"`
	PortfolioUrl         *string   `db:"portfolio_url" json:"portfolio_url"`
	EvidenceSummary      string    `db:"evidence_summary" json:"evidence_summary"`
	GithubUrl            string    `db:"github_url" json:"github_url"`
	CreatedAt            time.Time `db:"created_at" json:"created_at"`
	UpdatedAt            time.Time `db:"updated_at" json:"updated_at"`
}

func (q *Queries) UpsertProfile(ctx context.Context, arg UpsertProfileParams) (UpsertProfileRow, error) {
	row := q.db.QueryRow(ctx, upsertProfile,
		arg.UserID,
		arg.DisplayName,
		arg.PrimaryRole,
		arg.Bio,
		arg.Timezone,
		arg.WeeklyAvailability,
		arg.PreferredDuration,
		arg.WorkStyle,
		arg.CommunicationCadence,
		arg.Skills,
		arg.PortfolioUrl,
		arg.EvidenceSummary,
	)
	var i UpsertProfileRow
	err := row.Scan(
		&i.UserID,
		&i.DisplayName,
		&i.PrimaryRole,
		&i.Bio,
		&i.Timezone,
		&i.WeeklyAvailability,
		&i.PreferredDuration,
		&i.WorkStyle,
		&i.CommunicationCadence,
		&i.Skills,
		&i.PortfolioUrl,
		&i.EvidenceSummary,
		&i.GithubUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
