// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: safety_reports.sql

package database

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTrialFeedbackSafetyReport = `-- name: CreateTrialFeedbackSafetyReport :one
WITH report_target AS (
    SELECT
        feedback.id AS target_id,
        jsonb_build_object(
            'id', feedback.id,
            'proposalId', feedback.proposal_id,
            'authorUserId', feedback.author_user_id,
            'observedBehaviors', feedback.observed_behaviors,
            'collaborationExample', feedback.collaboration_example,
            'collaborateAgain', feedback.collaborate_again,
            'reviewSummary', feedback.review_summary,
            'submittedAt', feedback.submitted_at
        ) AS target_snapshot
    FROM trial_feedback AS feedback
    JOIN trial_proposals AS proposal ON proposal.id = feedback.proposal_id
    JOIN project_openings AS opening ON opening.id = proposal.opening_id
    WHERE feedback.id = $1
      AND feedback.author_user_id <> $2
      AND (
          proposal.applicant_user_id = $2
          OR opening.owner_user_id = $2
      )
), inserted AS (
    INSERT INTO safety_reports (
        id, reporter_user_id, target_kind, target_id, category, details, target_snapshot
    )
    SELECT
        $3, $2, 'trial_feedback',
        report_target.target_id, $4, $5, report_target.target_snapshot
    FROM report_target
    ON CONFLICT (reporter_user_id, target_kind, target_id) DO NOTHING
    RETURNING id, reporter_user_id, target_kind, target_id, category, details, target_snapshot, report_status, reviewed_by_user_id, moderator_notes, created_at, decided_at
)
SELECT inserted.id, inserted.reporter_user_id, inserted.target_kind, inserted.target_id, inserted.category, inserted.details, inserted.target_snapshot, inserted.report_status, inserted.reviewed_by_user_id, inserted.moderator_notes, inserted.created_at, inserted.decided_at, reporter.github_login AS reporter_github_login
FROM inserted
JOIN users AS reporter ON reporter.id = inserted.reporter_user_id
`

type CreateTrialFeedbackSafetyReportParams struct {
	TargetID       string `db:"target_id" json:"target_id"`
	ReporterUserID int64  `db:"reporter_user_id" json:"reporter_user_id"`
	ID             string `db:"id" json:"id"`
	Category       string `db:"category" json:"category"`
	Details        string `db:"details" json:"details"`
}

type CreateTrialFeedbackSafetyReportRow struct {
	ID                  string             `db:"id" json:"id"`
	ReporterUserID      int64              `db:"reporter_user_id" json:"reporter_user_id"`
	TargetKind          string             `db:"target_kind" json:"target_kind"`
	TargetID            string             `db:"target_id" json:"target_id"`
	Category            string             `db:"category" json:"category"`
	Details             string             `db:"details" json:"details"`
	TargetSnapshot      []byte             `db:"target_snapshot" json:"target_snapshot"`
	ReportStatus        string             `db:"report_status" json:"report_status"`
	ReviewedByUserID    *int64             `db:"reviewed_by_user_id" json:"reviewed_by_user_id"`
	ModeratorNotes      *string            `db:"moderator_notes" json:"moderator_notes"`
	CreatedAt           time.Time          `db:"created_at" json:"created_at"`
	DecidedAt           pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	ReporterGithubLogin string             `db:"reporter_github_login" json:"reporter_github_login"`
}

func (q *Queries) CreateTrialFeedbackSafetyReport(ctx context.Context, arg CreateTrialFeedbackSafetyReportParams) (CreateTrialFeedbackSafetyReportRow, error) {
	row := q.db.QueryRow(ctx, createTrialFeedbackSafetyReport,
		arg.TargetID,
		arg.ReporterUserID,
		arg.ID,
		arg.Category,
		arg.Details,
	)
	var i CreateTrialFeedbackSafetyReportRow
	err := row.Scan(
		&i.ID,
		&i.ReporterUserID,
		&i.TargetKind,
		&i.TargetID,
		&i.Category,
		&i.Details,
		&i.TargetSnapshot,
		&i.ReportStatus,
		&i.ReviewedByUserID,
		&i.ModeratorNotes,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.ReporterGithubLogin,
	)
	return i, err
}

const createTrustCandidateSafetyReport = `-- name: CreateTrustCandidateSafetyReport :one
WITH report_target AS (
    SELECT
        proposal.id AS target_id,
        jsonb_build_object(
            'proposalId', proposal.id,
            'outcomeStatus', outcome.outcome_status,
            'deliverableStatus', outcome.deliverable_status,
            'reviewStatus', outcome.review_status,
            'feedback', COALESCE((
                SELECT jsonb_agg(jsonb_build_object(
                    'id', feedback.id,
                    'authorUserId', feedback.author_user_id,
                    'observedBehaviors', feedback.observed_behaviors,
                    'collaborateAgain', feedback.collaborate_again,
                    'reviewSummary', feedback.review_summary,
                    'acknowledgedAt', feedback.acknowledged_at
                ) ORDER BY feedback.submitted_at ASC, feedback.id ASC)
                FROM trial_feedback AS feedback
                WHERE feedback.proposal_id = proposal.id
            ), '[]'::jsonb)
        ) AS target_snapshot
    FROM trial_proposals AS proposal
    JOIN project_openings AS opening ON opening.id = proposal.opening_id
    JOIN trial_outcomes AS outcome ON outcome.proposal_id = proposal.id
    WHERE proposal.id = $1
      AND outcome.review_status = 'confirmed'
      AND (
          proposal.applicant_user_id = $2
          OR opening.owner_user_id = $2
      )
), inserted AS (
    INSERT INTO safety_reports (
        id, reporter_user_id, target_kind, target_id, category, details, target_snapshot
    )
    SELECT
        $3, $2, 'trust_candidate',
        report_target.target_id, $4, $5, report_target.target_snapshot
    FROM report_target
    ON CONFLICT (reporter_user_id, target_kind, target_id) DO NOTHING
    RETURNING id, reporter_user_id, target_kind, target_id, category, details, target_snapshot, report_status, reviewed_by_user_id, moderator_notes, created_at, decided_at
)
SELECT inserted.id, inserted.reporter_user_id, inserted.target_kind, inserted.target_id, inserted.category, inserted.details, inserted.target_snapshot, inserted.report_status, inserted.reviewed_by_user_id, inserted.moderator_notes, inserted.created_at, inserted.decided_at, reporter.github_login AS reporter_github_login
FROM inserted
JOIN users AS reporter ON reporter.id = inserted.reporter_user_id
`

type CreateTrustCandidateSafetyReportParams struct {
	TargetID       string `db:"target_id" json:"target_id"`
	ReporterUserID int64  `db:"reporter_user_id" json:"reporter_user_id"`
	ID             string `db:"id" json:"id"`
	Category       string `db:"category" json:"category"`
	Details        string `db:"details" json:"details"`
}

type CreateTrustCandidateSafetyReportRow struct {
	ID                  string             `db:"id" json:"id"`
	ReporterUserID      int64              `db:"reporter_user_id" json:"reporter_user_id"`
	TargetKind          string             `db:"target_kind" json:"target_kind"`
	TargetID            string             `db:"target_id" json:"target_id"`
	Category            string             `db:"category" json:"category"`
	Details             string             `db:"details" json:"details"`
	TargetSnapshot      []byte             `db:"target_snapshot" json:"target_snapshot"`
	ReportStatus        string             `db:"report_status" json:"report_status"`
	ReviewedByUserID    *int64             `db:"reviewed_by_user_id" json:"reviewed_by_user_id"`
	ModeratorNotes      *string            `db:"moderator_notes" json:"moderator_notes"`
	CreatedAt           time.Time          `db:"created_at" json:"created_at"`
	DecidedAt           pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	ReporterGithubLogin string             `db:"reporter_github_login" json:"reporter_github_login"`
}

func (q *Queries) CreateTrustCandidateSafetyReport(ctx context.Context, arg CreateTrustCandidateSafetyReportParams) (CreateTrustCandidateSafetyReportRow, error) {
	row := q.db.QueryRow(ctx, createTrustCandidateSafetyReport,
		arg.TargetID,
		arg.ReporterUserID,
		arg.ID,
		arg.Category,
		arg.Details,
	)
	var i CreateTrustCandidateSafetyReportRow
	err := row.Scan(
		&i.ID,
		&i.ReporterUserID,
		&i.TargetKind,
		&i.TargetID,
		&i.Category,
		&i.Details,
		&i.TargetSnapshot,
		&i.ReportStatus,
		&i.ReviewedByUserID,
		&i.ModeratorNotes,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.ReporterGithubLogin,
	)
	return i, err
}

const decideSafetyReportForModerator = `-- name: DecideSafetyReportForModerator :one
WITH decided AS (
    UPDATE safety_reports AS report SET
        report_status = $1,
        reviewed_by_user_id = $2,
        moderator_notes = $3,
        decided_at = now()
    WHERE report.id = $4
      AND report.report_status = 'pending'
      AND $1::text IN ('upheld', 'dismissed')
      AND EXISTS (
          SELECT 1 FROM users AS moderator
          WHERE moderator.id = $2
            AND moderator.account_role = 'moderator'
      )
    RETURNING report.id, report.reporter_user_id, report.target_kind, report.target_id, report.category, report.details, report.target_snapshot, report.report_status, report.reviewed_by_user_id, report.moderator_notes, report.created_at, report.decided_at
)
SELECT decided.id, decided.reporter_user_id, decided.target_kind, decided.target_id, decided.category, decided.details, decided.target_snapshot, decided.report_status, decided.reviewed_by_user_id, decided.moderator_notes, decided.created_at, decided.decided_at, reporter.github_login AS reporter_github_login
FROM decided
JOIN users AS reporter ON reporter.id = decided.reporter_user_id
`

type DecideSafetyReportForModeratorParams struct {
	Decision        string  `db:"decision" json:"decision"`
	ModeratorUserID *int64  `db:"moderator_user_id" json:"moderator_user_id"`
	ModeratorNotes  *string `db:"moderator_notes" json:"moderator_notes"`
	ReportID        string  `db:"report_id" json:"report_id"`
}

type DecideSafetyReportForModeratorRow struct {
	ID                  string             `db:"id" json:"id"`
	ReporterUserID      int64              `db:"reporter_user_id" json:"reporter_user_id"`
	TargetKind          string             `db:"target_kind" json:"target_kind"`
	TargetID            string             `db:"target_id" json:"target_id"`
	Category            string             `db:"category" json:"category"`
	Details             string             `db:"details" json:"details"`
	TargetSnapshot      []byte             `db:"target_snapshot" json:"target_snapshot"`
	ReportStatus        string             `db:"report_status" json:"report_status"`
	ReviewedByUserID    *int64             `db:"reviewed_by_user_id" json:"reviewed_by_user_id"`
	ModeratorNotes      *string            `db:"moderator_notes" json:"moderator_notes"`
	CreatedAt           time.Time          `db:"created_at" json:"created_at"`
	DecidedAt           pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	ReporterGithubLogin string             `db:"reporter_github_login" json:"reporter_github_login"`
}

func (q *Queries) DecideSafetyReportForModerator(ctx context.Context, arg DecideSafetyReportForModeratorParams) (DecideSafetyReportForModeratorRow, error) {
	row := q.db.QueryRow(ctx, decideSafetyReportForModerator,
		arg.Decision,
		arg.ModeratorUserID,
		arg.ModeratorNotes,
		arg.ReportID,
	)
	var i DecideSafetyReportForModeratorRow
	err := row.Scan(
		&i.ID,
		&i.ReporterUserID,
		&i.TargetKind,
		&i.TargetID,
		&i.Category,
		&i.Details,
		&i.TargetSnapshot,
		&i.ReportStatus,
		&i.ReviewedByUserID,
		&i.ModeratorNotes,
		&i.CreatedAt,
		&i.DecidedAt,
		&i.ReporterGithubLogin,
	)
	return i, err
}

const getModeratorSafetyScope = `-- name: GetModeratorSafetyScope :one
SELECT id
FROM users
WHERE id = $1
  AND account_role = 'moderator'
`

func (q *Queries) GetModeratorSafetyScope(ctx context.Context, moderatorUserID int64) (int64, error) {
	row := q.db.QueryRow(ctx, getModeratorSafetyScope, moderatorUserID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listSafetyReportsForModerator = `-- name: ListSafetyReportsForModerator :many
SELECT report.id, report.reporter_user_id, report.target_kind, report.target_id, report.category, report.details, report.target_snapshot, report.report_status, report.reviewed_by_user_id, report.moderator_notes, report.created_at, report.decided_at, reporter.github_login AS reporter_github_login
FROM safety_reports AS report
JOIN users AS reporter ON reporter.id = report.reporter_user_id
WHERE EXISTS (
    SELECT 1 FROM users AS moderator
    WHERE moderator.id = $1
      AND moderator.account_role = 'moderator'
)
ORDER BY
    CASE WHEN report.report_status = 'pending' THEN 0 ELSE 1 END,
    report.created_at ASC,
    report.id ASC
`

type ListSafetyReportsForModeratorRow struct {
	ID                  string             `db:"id" json:"id"`
	ReporterUserID      int64              `db:"reporter_user_id" json:"reporter_user_id"`
	TargetKind          string             `db:"target_kind" json:"target_kind"`
	TargetID            string             `db:"target_id" json:"target_id"`
	Category            string             `db:"category" json:"category"`
	Details             string             `db:"details" json:"details"`
	TargetSnapshot      []byte             `db:"target_snapshot" json:"target_snapshot"`
	ReportStatus        string             `db:"report_status" json:"report_status"`
	ReviewedByUserID    *int64             `db:"reviewed_by_user_id" json:"reviewed_by_user_id"`
	ModeratorNotes      *string            `db:"moderator_notes" json:"moderator_notes"`
	CreatedAt           time.Time          `db:"created_at" json:"created_at"`
	DecidedAt           pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	ReporterGithubLogin string             `db:"reporter_github_login" json:"reporter_github_login"`
}

func (q *Queries) ListSafetyReportsForModerator(ctx context.Context, moderatorUserID int64) ([]ListSafetyReportsForModeratorRow, error) {
	rows, err := q.db.Query(ctx, listSafetyReportsForModerator, moderatorUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSafetyReportsForModeratorRow{}
	for rows.Next() {
		var i ListSafetyReportsForModeratorRow
		if err := rows.Scan(
			&i.ID,
			&i.ReporterUserID,
			&i.TargetKind,
			&i.TargetID,
			&i.Category,
			&i.Details,
			&i.TargetSnapshot,
			&i.ReportStatus,
			&i.ReviewedByUserID,
			&i.ModeratorNotes,
			&i.CreatedAt,
			&i.DecidedAt,
			&i.ReporterGithubLogin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
