// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trial_proposals.sql

package database

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTrialCheckInForParticipant = `-- name: CreateTrialCheckInForParticipant :one
WITH inserted AS (
    INSERT INTO trial_check_ins (
        id, proposal_id, author_user_id, check_in_kind, update_text, evidence_url
    )
    SELECT
        $1, proposal.id, $2,
        $3, $4, $5
    FROM trial_proposals AS proposal
    JOIN project_openings AS opening ON opening.id = proposal.opening_id
    WHERE proposal.id = $6
      AND proposal.proposal_status = 'accepted'
      AND (
          proposal.applicant_user_id = $2
          OR opening.owner_user_id = $2
      )
    RETURNING id, proposal_id, author_user_id, check_in_kind, update_text, evidence_url, created_at
)
SELECT
    inserted.id, inserted.proposal_id, inserted.author_user_id,
    inserted.check_in_kind, inserted.update_text, inserted.evidence_url,
    inserted.created_at, profiles.display_name AS author_display_name,
    CASE
        WHEN inserted.author_user_id = proposal.applicant_user_id THEN 'applicant'
        ELSE 'owner'
    END AS author_role
FROM inserted
JOIN trial_proposals AS proposal ON proposal.id = inserted.proposal_id
JOIN profiles ON profiles.user_id = inserted.author_user_id
`

type CreateTrialCheckInForParticipantParams struct {
	ID           string `db:"id" json:"id"`
	AuthorUserID int64  `db:"author_user_id" json:"author_user_id"`
	CheckInKind  string `db:"check_in_kind" json:"check_in_kind"`
	UpdateText   string `db:"update_text" json:"update_text"`
	EvidenceUrl  string `db:"evidence_url" json:"evidence_url"`
	ProposalID   string `db:"proposal_id" json:"proposal_id"`
}

type CreateTrialCheckInForParticipantRow struct {
	ID                string    `db:"id" json:"id"`
	ProposalID        string    `db:"proposal_id" json:"proposal_id"`
	AuthorUserID      int64     `db:"author_user_id" json:"author_user_id"`
	CheckInKind       string    `db:"check_in_kind" json:"check_in_kind"`
	UpdateText        string    `db:"update_text" json:"update_text"`
	EvidenceUrl       string    `db:"evidence_url" json:"evidence_url"`
	CreatedAt         time.Time `db:"created_at" json:"created_at"`
	AuthorDisplayName string    `db:"author_display_name" json:"author_display_name"`
	AuthorRole        string    `db:"author_role" json:"author_role"`
}

func (q *Queries) CreateTrialCheckInForParticipant(ctx context.Context, arg CreateTrialCheckInForParticipantParams) (CreateTrialCheckInForParticipantRow, error) {
	row := q.db.QueryRow(ctx, createTrialCheckInForParticipant,
		arg.ID,
		arg.AuthorUserID,
		arg.CheckInKind,
		arg.UpdateText,
		arg.EvidenceUrl,
		arg.ProposalID,
	)
	var i CreateTrialCheckInForParticipantRow
	err := row.Scan(
		&i.ID,
		&i.ProposalID,
		&i.AuthorUserID,
		&i.CheckInKind,
		&i.UpdateText,
		&i.EvidenceUrl,
		&i.CreatedAt,
		&i.AuthorDisplayName,
		&i.AuthorRole,
	)
	return i, err
}

const createTrialOutcomeForParticipant = `-- name: CreateTrialOutcomeForParticipant :one
WITH inserted AS (
    INSERT INTO trial_outcomes (
        id, proposal_id, submitted_by_user_id, outcome_status,
        deliverable_status, work_summary, evidence_url, closeout_notes
    )
    SELECT
        $1, proposal.id, $2,
        $3, $4,
        $5, $6, $7
    FROM trial_proposals AS proposal
    JOIN project_openings AS opening ON opening.id = proposal.opening_id
    WHERE proposal.id = $8
      AND proposal.proposal_status = 'accepted'
      AND (
          proposal.applicant_user_id = $2
          OR opening.owner_user_id = $2
      )
    ON CONFLICT (proposal_id) DO NOTHING
    RETURNING id, proposal_id, submitted_by_user_id, outcome_status, deliverable_status, work_summary, evidence_url, closeout_notes, review_status, decided_by_user_id, submitted_at, decided_at
)
SELECT
    inserted.id, inserted.proposal_id, inserted.submitted_by_user_id,
    inserted.outcome_status, inserted.deliverable_status, inserted.work_summary,
    inserted.evidence_url, inserted.closeout_notes, inserted.review_status,
    inserted.submitted_at, inserted.decided_at,
    profiles.display_name AS submitted_by_display_name,
    CASE
        WHEN inserted.submitted_by_user_id = proposal.applicant_user_id THEN 'applicant'
        ELSE 'owner'
    END AS submitted_by_role,
    false AS can_decide
FROM inserted
JOIN trial_proposals AS proposal ON proposal.id = inserted.proposal_id
JOIN profiles ON profiles.user_id = inserted.submitted_by_user_id
`

type CreateTrialOutcomeForParticipantParams struct {
	ID                string `db:"id" json:"id"`
	SubmittedByUserID int64  `db:"submitted_by_user_id" json:"submitted_by_user_id"`
	OutcomeStatus     string `db:"outcome_status" json:"outcome_status"`
	DeliverableStatus string `db:"deliverable_status" json:"deliverable_status"`
	WorkSummary       string `db:"work_summary" json:"work_summary"`
	EvidenceUrl       string `db:"evidence_url" json:"evidence_url"`
	CloseoutNotes     string `db:"closeout_notes" json:"closeout_notes"`
	ProposalID        string `db:"proposal_id" json:"proposal_id"`
}

type CreateTrialOutcomeForParticipantRow struct {
	ID                     string             `db:"id" json:"id"`
	ProposalID             string             `db:"proposal_id" json:"proposal_id"`
	SubmittedByUserID      int64              `db:"submitted_by_user_id" json:"submitted_by_user_id"`
	OutcomeStatus          string             `db:"outcome_status" json:"outcome_status"`
	DeliverableStatus      string             `db:"deliverable_status" json:"deliverable_status"`
	WorkSummary            string             `db:"work_summary" json:"work_summary"`
	EvidenceUrl            string             `db:"evidence_url" json:"evidence_url"`
	CloseoutNotes          string             `db:"closeout_notes" json:"closeout_notes"`
	ReviewStatus           string             `db:"review_status" json:"review_status"`
	SubmittedAt            time.Time          `db:"submitted_at" json:"submitted_at"`
	DecidedAt              pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	SubmittedByDisplayName string             `db:"submitted_by_display_name" json:"submitted_by_display_name"`
	SubmittedByRole        string             `db:"submitted_by_role" json:"submitted_by_role"`
	CanDecide              bool               `db:"can_decide" json:"can_decide"`
}

func (q *Queries) CreateTrialOutcomeForParticipant(ctx context.Context, arg CreateTrialOutcomeForParticipantParams) (CreateTrialOutcomeForParticipantRow, error) {
	row := q.db.QueryRow(ctx, createTrialOutcomeForParticipant,
		arg.ID,
		arg.SubmittedByUserID,
		arg.OutcomeStatus,
		arg.DeliverableStatus,
		arg.WorkSummary,
		arg.EvidenceUrl,
		arg.CloseoutNotes,
		arg.ProposalID,
	)
	var i CreateTrialOutcomeForParticipantRow
	err := row.Scan(
		&i.ID,
		&i.ProposalID,
		&i.SubmittedByUserID,
		&i.OutcomeStatus,
		&i.DeliverableStatus,
		&i.WorkSummary,
		&i.EvidenceUrl,
		&i.CloseoutNotes,
		&i.ReviewStatus,
		&i.SubmittedAt,
		&i.DecidedAt,
		&i.SubmittedByDisplayName,
		&i.SubmittedByRole,
		&i.CanDecide,
	)
	return i, err
}

const decideTrialOutcomeForParticipant = `-- name: DecideTrialOutcomeForParticipant :one
WITH decided AS (
    UPDATE trial_outcomes AS outcome SET
        review_status = $1,
        decided_by_user_id = $2,
        decided_at = now()
    FROM trial_proposals AS proposal
    JOIN project_openings AS opening ON opening.id = proposal.opening_id
    WHERE outcome.proposal_id = $3
      AND proposal.id = outcome.proposal_id
      AND proposal.proposal_status = 'accepted'
      AND outcome.review_status = 'pending'
      AND outcome.submitted_by_user_id <> $2
      AND (
          proposal.applicant_user_id = $2
          OR opening.owner_user_id = $2
      )
      AND $1::text IN ('confirmed', 'disputed')
    RETURNING outcome.id, outcome.proposal_id, outcome.submitted_by_user_id, outcome.outcome_status, outcome.deliverable_status, outcome.work_summary, outcome.evidence_url, outcome.closeout_notes, outcome.review_status, outcome.decided_by_user_id, outcome.submitted_at, outcome.decided_at
)
SELECT
    decided.id, decided.proposal_id, decided.submitted_by_user_id,
    decided.outcome_status, decided.deliverable_status, decided.work_summary,
    decided.evidence_url, decided.closeout_notes, decided.review_status,
    decided.submitted_at, decided.decided_at,
    profiles.display_name AS submitted_by_display_name,
    CASE
        WHEN decided.submitted_by_user_id = proposal.applicant_user_id THEN 'applicant'
        ELSE 'owner'
    END AS submitted_by_role,
    false AS can_decide
FROM decided
JOIN trial_proposals AS proposal ON proposal.id = decided.proposal_id
JOIN profiles ON profiles.user_id = decided.submitted_by_user_id
`

type DecideTrialOutcomeForParticipantParams struct {
	Decision          string `db:"decision" json:"decision"`
	ParticipantUserID *int64 `db:"participant_user_id" json:"participant_user_id"`
	ProposalID        string `db:"proposal_id" json:"proposal_id"`
}

type DecideTrialOutcomeForParticipantRow struct {
	ID                     string             `db:"id" json:"id"`
	ProposalID             string             `db:"proposal_id" json:"proposal_id"`
	SubmittedByUserID      int64              `db:"submitted_by_user_id" json:"submitted_by_user_id"`
	OutcomeStatus          string             `db:"outcome_status" json:"outcome_status"`
	DeliverableStatus      string             `db:"deliverable_status" json:"deliverable_status"`
	WorkSummary            string             `db:"work_summary" json:"work_summary"`
	EvidenceUrl            string             `db:"evidence_url" json:"evidence_url"`
	CloseoutNotes          string             `db:"closeout_notes" json:"closeout_notes"`
	ReviewStatus           string             `db:"review_status" json:"review_status"`
	SubmittedAt            time.Time          `db:"submitted_at" json:"submitted_at"`
	DecidedAt              pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	SubmittedByDisplayName string             `db:"submitted_by_display_name" json:"submitted_by_display_name"`
	SubmittedByRole        string             `db:"submitted_by_role" json:"submitted_by_role"`
	CanDecide              bool               `db:"can_decide" json:"can_decide"`
}

func (q *Queries) DecideTrialOutcomeForParticipant(ctx context.Context, arg DecideTrialOutcomeForParticipantParams) (DecideTrialOutcomeForParticipantRow, error) {
	row := q.db.QueryRow(ctx, decideTrialOutcomeForParticipant, arg.Decision, arg.ParticipantUserID, arg.ProposalID)
	var i DecideTrialOutcomeForParticipantRow
	err := row.Scan(
		&i.ID,
		&i.ProposalID,
		&i.SubmittedByUserID,
		&i.OutcomeStatus,
		&i.DeliverableStatus,
		&i.WorkSummary,
		&i.EvidenceUrl,
		&i.CloseoutNotes,
		&i.ReviewStatus,
		&i.SubmittedAt,
		&i.DecidedAt,
		&i.SubmittedByDisplayName,
		&i.SubmittedByRole,
		&i.CanDecide,
	)
	return i, err
}

const decideTrialProposalForOwner = `-- name: DecideTrialProposalForOwner :one
UPDATE trial_proposals AS proposal SET
    proposal_status = $1,
    decided_at = now(),
    updated_at = now()
FROM project_openings AS opening
WHERE proposal.id = $2
  AND proposal.opening_id = $3
  AND proposal.proposal_status = 'sent'
  AND opening.id = proposal.opening_id
  AND opening.owner_user_id = $4
  AND $1::text IN ('accepted', 'declined')
RETURNING proposal.id, proposal.application_id, proposal.opening_id, proposal.applicant_user_id, proposal.outcome, proposal.deliverable, proposal.non_goals, proposal.start_date, proposal.end_date, proposal.weekly_hours, proposal.check_in_cadence, proposal.access_level, proposal.confidentiality, proposal.ip_ownership, proposal.exit_plan, proposal.terms_confirmed, proposal.proposal_status, proposal.created_at, proposal.updated_at, proposal.sent_at, proposal.decided_at
`

type DecideTrialProposalForOwnerParams struct {
	Decision    string `db:"decision" json:"decision"`
	ProposalID  string `db:"proposal_id" json:"proposal_id"`
	OpeningID   string `db:"opening_id" json:"opening_id"`
	OwnerUserID *int64 `db:"owner_user_id" json:"owner_user_id"`
}

func (q *Queries) DecideTrialProposalForOwner(ctx context.Context, arg DecideTrialProposalForOwnerParams) (TrialProposal, error) {
	row := q.db.QueryRow(ctx, decideTrialProposalForOwner,
		arg.Decision,
		arg.ProposalID,
		arg.OpeningID,
		arg.OwnerUserID,
	)
	var i TrialProposal
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.OpeningID,
		&i.ApplicantUserID,
		&i.Outcome,
		&i.Deliverable,
		&i.NonGoals,
		&i.StartDate,
		&i.EndDate,
		&i.WeeklyHours,
		&i.CheckInCadence,
		&i.AccessLevel,
		&i.Confidentiality,
		&i.IpOwnership,
		&i.ExitPlan,
		&i.TermsConfirmed,
		&i.ProposalStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
		&i.DecidedAt,
	)
	return i, err
}

const getOwnTrialProposal = `-- name: GetOwnTrialProposal :one
SELECT
    proposal.id, proposal.application_id, proposal.opening_id,
    proposal.applicant_user_id, proposal.outcome, proposal.deliverable,
    proposal.non_goals, proposal.start_date, proposal.end_date,
    proposal.weekly_hours, proposal.check_in_cadence, proposal.access_level,
    proposal.confidentiality, proposal.ip_ownership, proposal.exit_plan,
    proposal.terms_confirmed, proposal.proposal_status,
    proposal.created_at, proposal.updated_at, proposal.sent_at, proposal.decided_at
FROM trial_proposals AS proposal
JOIN applications AS application ON application.id = proposal.application_id
WHERE proposal.opening_id = $1
  AND proposal.applicant_user_id = $2
  AND application.status = 'accepted'
`

type GetOwnTrialProposalParams struct {
	OpeningID       string `db:"opening_id" json:"opening_id"`
	ApplicantUserID int64  `db:"applicant_user_id" json:"applicant_user_id"`
}

func (q *Queries) GetOwnTrialProposal(ctx context.Context, arg GetOwnTrialProposalParams) (TrialProposal, error) {
	row := q.db.QueryRow(ctx, getOwnTrialProposal, arg.OpeningID, arg.ApplicantUserID)
	var i TrialProposal
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.OpeningID,
		&i.ApplicantUserID,
		&i.Outcome,
		&i.Deliverable,
		&i.NonGoals,
		&i.StartDate,
		&i.EndDate,
		&i.WeeklyHours,
		&i.CheckInCadence,
		&i.AccessLevel,
		&i.Confidentiality,
		&i.IpOwnership,
		&i.ExitPlan,
		&i.TermsConfirmed,
		&i.ProposalStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
		&i.DecidedAt,
	)
	return i, err
}

const getOwnedOpeningTrialProposalReviewScope = `-- name: GetOwnedOpeningTrialProposalReviewScope :one
SELECT id
FROM project_openings
WHERE id = $1
  AND owner_user_id = $2
`

type GetOwnedOpeningTrialProposalReviewScopeParams struct {
	OpeningID   string `db:"opening_id" json:"opening_id"`
	OwnerUserID *int64 `db:"owner_user_id" json:"owner_user_id"`
}

func (q *Queries) GetOwnedOpeningTrialProposalReviewScope(ctx context.Context, arg GetOwnedOpeningTrialProposalReviewScopeParams) (string, error) {
	row := q.db.QueryRow(ctx, getOwnedOpeningTrialProposalReviewScope, arg.OpeningID, arg.OwnerUserID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const getTrialOutcomeForParticipant = `-- name: GetTrialOutcomeForParticipant :one
SELECT
    outcome.id, outcome.proposal_id, outcome.submitted_by_user_id,
    outcome.outcome_status, outcome.deliverable_status, outcome.work_summary,
    outcome.evidence_url, outcome.closeout_notes, outcome.review_status,
    outcome.submitted_at, outcome.decided_at,
    profiles.display_name AS submitted_by_display_name,
    CASE
        WHEN outcome.submitted_by_user_id = proposal.applicant_user_id THEN 'applicant'
        ELSE 'owner'
    END AS submitted_by_role,
    (
        outcome.review_status = 'pending'
        AND outcome.submitted_by_user_id <> $1
    ) AS can_decide
FROM trial_outcomes AS outcome
JOIN trial_proposals AS proposal ON proposal.id = outcome.proposal_id
JOIN project_openings AS opening ON opening.id = proposal.opening_id
JOIN profiles ON profiles.user_id = outcome.submitted_by_user_id
WHERE outcome.proposal_id = $2
  AND proposal.proposal_status = 'accepted'
  AND (
      proposal.applicant_user_id = $1
      OR opening.owner_user_id = $1
  )
`

type GetTrialOutcomeForParticipantParams struct {
	ParticipantUserID int64  `db:"participant_user_id" json:"participant_user_id"`
	ProposalID        string `db:"proposal_id" json:"proposal_id"`
}

type GetTrialOutcomeForParticipantRow struct {
	ID                     string             `db:"id" json:"id"`
	ProposalID             string             `db:"proposal_id" json:"proposal_id"`
	SubmittedByUserID      int64              `db:"submitted_by_user_id" json:"submitted_by_user_id"`
	OutcomeStatus          string             `db:"outcome_status" json:"outcome_status"`
	DeliverableStatus      string             `db:"deliverable_status" json:"deliverable_status"`
	WorkSummary            string             `db:"work_summary" json:"work_summary"`
	EvidenceUrl            string             `db:"evidence_url" json:"evidence_url"`
	CloseoutNotes          string             `db:"closeout_notes" json:"closeout_notes"`
	ReviewStatus           string             `db:"review_status" json:"review_status"`
	SubmittedAt            time.Time          `db:"submitted_at" json:"submitted_at"`
	DecidedAt              pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	SubmittedByDisplayName string             `db:"submitted_by_display_name" json:"submitted_by_display_name"`
	SubmittedByRole        string             `db:"submitted_by_role" json:"submitted_by_role"`
	CanDecide              *bool              `db:"can_decide" json:"can_decide"`
}

func (q *Queries) GetTrialOutcomeForParticipant(ctx context.Context, arg GetTrialOutcomeForParticipantParams) (GetTrialOutcomeForParticipantRow, error) {
	row := q.db.QueryRow(ctx, getTrialOutcomeForParticipant, arg.ParticipantUserID, arg.ProposalID)
	var i GetTrialOutcomeForParticipantRow
	err := row.Scan(
		&i.ID,
		&i.ProposalID,
		&i.SubmittedByUserID,
		&i.OutcomeStatus,
		&i.DeliverableStatus,
		&i.WorkSummary,
		&i.EvidenceUrl,
		&i.CloseoutNotes,
		&i.ReviewStatus,
		&i.SubmittedAt,
		&i.DecidedAt,
		&i.SubmittedByDisplayName,
		&i.SubmittedByRole,
		&i.CanDecide,
	)
	return i, err
}

const getTrialWorkspaceForParticipant = `-- name: GetTrialWorkspaceForParticipant :one
SELECT proposal.id
FROM trial_proposals AS proposal
JOIN project_openings AS opening ON opening.id = proposal.opening_id
WHERE proposal.id = $1
  AND proposal.proposal_status = 'accepted'
  AND (
      proposal.applicant_user_id = $2
      OR opening.owner_user_id = $2
  )
`

type GetTrialWorkspaceForParticipantParams struct {
	ProposalID        string `db:"proposal_id" json:"proposal_id"`
	ParticipantUserID int64  `db:"participant_user_id" json:"participant_user_id"`
}

func (q *Queries) GetTrialWorkspaceForParticipant(ctx context.Context, arg GetTrialWorkspaceForParticipantParams) (string, error) {
	row := q.db.QueryRow(ctx, getTrialWorkspaceForParticipant, arg.ProposalID, arg.ParticipantUserID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const listTrialCheckInsForParticipant = `-- name: ListTrialCheckInsForParticipant :many
SELECT
    check_in.id, check_in.proposal_id, check_in.author_user_id,
    check_in.check_in_kind, check_in.update_text, check_in.evidence_url,
    check_in.created_at, profiles.display_name AS author_display_name,
    CASE
        WHEN check_in.author_user_id = proposal.applicant_user_id THEN 'applicant'
        ELSE 'owner'
    END AS author_role
FROM trial_check_ins AS check_in
JOIN trial_proposals AS proposal ON proposal.id = check_in.proposal_id
JOIN project_openings AS opening ON opening.id = proposal.opening_id
JOIN profiles ON profiles.user_id = check_in.author_user_id
WHERE check_in.proposal_id = $1
  AND proposal.proposal_status = 'accepted'
  AND (
      proposal.applicant_user_id = $2
      OR opening.owner_user_id = $2
  )
ORDER BY check_in.created_at ASC, check_in.id ASC
`

type ListTrialCheckInsForParticipantParams struct {
	ProposalID        string `db:"proposal_id" json:"proposal_id"`
	ParticipantUserID int64  `db:"participant_user_id" json:"participant_user_id"`
}

type ListTrialCheckInsForParticipantRow struct {
	ID                string    `db:"id" json:"id"`
	ProposalID        string    `db:"proposal_id" json:"proposal_id"`
	AuthorUserID      int64     `db:"author_user_id" json:"author_user_id"`
	CheckInKind       string    `db:"check_in_kind" json:"check_in_kind"`
	UpdateText        string    `db:"update_text" json:"update_text"`
	EvidenceUrl       string    `db:"evidence_url" json:"evidence_url"`
	CreatedAt         time.Time `db:"created_at" json:"created_at"`
	AuthorDisplayName string    `db:"author_display_name" json:"author_display_name"`
	AuthorRole        string    `db:"author_role" json:"author_role"`
}

func (q *Queries) ListTrialCheckInsForParticipant(ctx context.Context, arg ListTrialCheckInsForParticipantParams) ([]ListTrialCheckInsForParticipantRow, error) {
	rows, err := q.db.Query(ctx, listTrialCheckInsForParticipant, arg.ProposalID, arg.ParticipantUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrialCheckInsForParticipantRow{}
	for rows.Next() {
		var i ListTrialCheckInsForParticipantRow
		if err := rows.Scan(
			&i.ID,
			&i.ProposalID,
			&i.AuthorUserID,
			&i.CheckInKind,
			&i.UpdateText,
			&i.EvidenceUrl,
			&i.CreatedAt,
			&i.AuthorDisplayName,
			&i.AuthorRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrialProposalsForOwner = `-- name: ListTrialProposalsForOwner :many
SELECT
    proposal.id, proposal.application_id, proposal.opening_id,
    proposal.applicant_user_id, proposal.outcome, proposal.deliverable,
    proposal.non_goals, proposal.start_date, proposal.end_date,
    proposal.weekly_hours, proposal.check_in_cadence, proposal.access_level,
    proposal.confidentiality, proposal.ip_ownership, proposal.exit_plan,
    proposal.terms_confirmed, proposal.proposal_status,
    proposal.created_at, proposal.updated_at, proposal.sent_at, proposal.decided_at,
    profiles.display_name AS applicant_display_name,
    profiles.primary_role AS applicant_primary_role,
    users.profile_url AS applicant_github_url
FROM trial_proposals AS proposal
JOIN project_openings AS opening ON opening.id = proposal.opening_id
JOIN profiles ON profiles.user_id = proposal.applicant_user_id
JOIN users ON users.id = proposal.applicant_user_id
WHERE proposal.opening_id = $1
  AND opening.owner_user_id = $2
  AND proposal.proposal_status IN ('sent', 'accepted', 'declined')
ORDER BY proposal.sent_at ASC, proposal.id ASC
`

type ListTrialProposalsForOwnerParams struct {
	OpeningID   string `db:"opening_id" json:"opening_id"`
	OwnerUserID *int64 `db:"owner_user_id" json:"owner_user_id"`
}

type ListTrialProposalsForOwnerRow struct {
	ID                   string             `db:"id" json:"id"`
	ApplicationID        string             `db:"application_id" json:"application_id"`
	OpeningID            string             `db:"opening_id" json:"opening_id"`
	ApplicantUserID      int64              `db:"applicant_user_id" json:"applicant_user_id"`
	Outcome              string             `db:"outcome" json:"outcome"`
	Deliverable          string             `db:"deliverable" json:"deliverable"`
	NonGoals             string             `db:"non_goals" json:"non_goals"`
	StartDate            pgtype.Date        `db:"start_date" json:"start_date"`
	EndDate              pgtype.Date        `db:"end_date" json:"end_date"`
	WeeklyHours          int32              `db:"weekly_hours" json:"weekly_hours"`
	CheckInCadence       string             `db:"check_in_cadence" json:"check_in_cadence"`
	AccessLevel          string             `db:"access_level" json:"access_level"`
	Confidentiality      string             `db:"confidentiality" json:"confidentiality"`
	IpOwnership          string             `db:"ip_ownership" json:"ip_ownership"`
	ExitPlan             string             `db:"exit_plan" json:"exit_plan"`
	TermsConfirmed       bool               `db:"terms_confirmed" json:"terms_confirmed"`
	ProposalStatus       string             `db:"proposal_status" json:"proposal_status"`
	CreatedAt            time.Time          `db:"created_at" json:"created_at"`
	UpdatedAt            time.Time          `db:"updated_at" json:"updated_at"`
	SentAt               pgtype.Timestamptz `db:"sent_at" json:"sent_at"`
	DecidedAt            pgtype.Timestamptz `db:"decided_at" json:"decided_at"`
	ApplicantDisplayName string             `db:"applicant_display_name" json:"applicant_display_name"`
	ApplicantPrimaryRole string             `db:"applicant_primary_role" json:"applicant_primary_role"`
	ApplicantGithubUrl   string             `db:"applicant_github_url" json:"applicant_github_url"`
}

func (q *Queries) ListTrialProposalsForOwner(ctx context.Context, arg ListTrialProposalsForOwnerParams) ([]ListTrialProposalsForOwnerRow, error) {
	rows, err := q.db.Query(ctx, listTrialProposalsForOwner, arg.OpeningID, arg.OwnerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTrialProposalsForOwnerRow{}
	for rows.Next() {
		var i ListTrialProposalsForOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.ApplicationID,
			&i.OpeningID,
			&i.ApplicantUserID,
			&i.Outcome,
			&i.Deliverable,
			&i.NonGoals,
			&i.StartDate,
			&i.EndDate,
			&i.WeeklyHours,
			&i.CheckInCadence,
			&i.AccessLevel,
			&i.Confidentiality,
			&i.IpOwnership,
			&i.ExitPlan,
			&i.TermsConfirmed,
			&i.ProposalStatus,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SentAt,
			&i.DecidedAt,
			&i.ApplicantDisplayName,
			&i.ApplicantPrimaryRole,
			&i.ApplicantGithubUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sendOwnTrialProposal = `-- name: SendOwnTrialProposal :one
UPDATE trial_proposals AS proposal SET
    proposal_status = 'sent',
    sent_at = now(),
    updated_at = now()
FROM applications AS application
WHERE proposal.opening_id = $1
  AND proposal.applicant_user_id = $2
  AND proposal.proposal_status = 'draft'
  AND application.id = proposal.application_id
  AND application.status = 'accepted'
RETURNING proposal.id, proposal.application_id, proposal.opening_id, proposal.applicant_user_id, proposal.outcome, proposal.deliverable, proposal.non_goals, proposal.start_date, proposal.end_date, proposal.weekly_hours, proposal.check_in_cadence, proposal.access_level, proposal.confidentiality, proposal.ip_ownership, proposal.exit_plan, proposal.terms_confirmed, proposal.proposal_status, proposal.created_at, proposal.updated_at, proposal.sent_at, proposal.decided_at
`

type SendOwnTrialProposalParams struct {
	OpeningID       string `db:"opening_id" json:"opening_id"`
	ApplicantUserID int64  `db:"applicant_user_id" json:"applicant_user_id"`
}

func (q *Queries) SendOwnTrialProposal(ctx context.Context, arg SendOwnTrialProposalParams) (TrialProposal, error) {
	row := q.db.QueryRow(ctx, sendOwnTrialProposal, arg.OpeningID, arg.ApplicantUserID)
	var i TrialProposal
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.OpeningID,
		&i.ApplicantUserID,
		&i.Outcome,
		&i.Deliverable,
		&i.NonGoals,
		&i.StartDate,
		&i.EndDate,
		&i.WeeklyHours,
		&i.CheckInCadence,
		&i.AccessLevel,
		&i.Confidentiality,
		&i.IpOwnership,
		&i.ExitPlan,
		&i.TermsConfirmed,
		&i.ProposalStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
		&i.DecidedAt,
	)
	return i, err
}

const upsertOwnTrialProposalDraft = `-- name: UpsertOwnTrialProposalDraft :one
INSERT INTO trial_proposals (
    id, application_id, opening_id, applicant_user_id, outcome, deliverable,
    non_goals, start_date, end_date, weekly_hours, check_in_cadence,
    access_level, confidentiality, ip_ownership, exit_plan, terms_confirmed
)
SELECT
    $1, application.id, application.opening_id,
    application.applicant_user_id, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12,
    $13
FROM applications AS application
WHERE application.opening_id = $14
  AND application.applicant_user_id = $15
  AND application.status = 'accepted'
ON CONFLICT (application_id) DO UPDATE SET
    outcome = EXCLUDED.outcome,
    deliverable = EXCLUDED.deliverable,
    non_goals = EXCLUDED.non_goals,
    start_date = EXCLUDED.start_date,
    end_date = EXCLUDED.end_date,
    weekly_hours = EXCLUDED.weekly_hours,
    check_in_cadence = EXCLUDED.check_in_cadence,
    access_level = EXCLUDED.access_level,
    confidentiality = EXCLUDED.confidentiality,
    ip_ownership = EXCLUDED.ip_ownership,
    exit_plan = EXCLUDED.exit_plan,
    terms_confirmed = EXCLUDED.terms_confirmed,
    updated_at = now()
WHERE trial_proposals.proposal_status = 'draft'
RETURNING
    id, application_id, opening_id, applicant_user_id, outcome, deliverable,
    non_goals, start_date, end_date, weekly_hours, check_in_cadence,
    access_level, confidentiality, ip_ownership, exit_plan, terms_confirmed,
    proposal_status, created_at, updated_at, sent_at, decided_at
`

type UpsertOwnTrialProposalDraftParams struct {
	ID              string      `db:"id" json:"id"`
	Outcome         string      `db:"outcome" json:"outcome"`
	Deliverable     string      `db:"deliverable" json:"deliverable"`
	NonGoals        string      `db:"non_goals" json:"non_goals"`
	StartDate       pgtype.Date `db:"start_date" json:"start_date"`
	EndDate         pgtype.Date `db:"end_date" json:"end_date"`
	WeeklyHours     int32       `db:"weekly_hours" json:"weekly_hours"`
	CheckInCadence  string      `db:"check_in_cadence" json:"check_in_cadence"`
	AccessLevel     string      `db:"access_level" json:"access_level"`
	Confidentiality string      `db:"confidentiality" json:"confidentiality"`
	IpOwnership     string      `db:"ip_ownership" json:"ip_ownership"`
	ExitPlan        string      `db:"exit_plan" json:"exit_plan"`
	TermsConfirmed  bool        `db:"terms_confirmed" json:"terms_confirmed"`
	OpeningID       string      `db:"opening_id" json:"opening_id"`
	ApplicantUserID int64       `db:"applicant_user_id" json:"applicant_user_id"`
}

func (q *Queries) UpsertOwnTrialProposalDraft(ctx context.Context, arg UpsertOwnTrialProposalDraftParams) (TrialProposal, error) {
	row := q.db.QueryRow(ctx, upsertOwnTrialProposalDraft,
		arg.ID,
		arg.Outcome,
		arg.Deliverable,
		arg.NonGoals,
		arg.StartDate,
		arg.EndDate,
		arg.WeeklyHours,
		arg.CheckInCadence,
		arg.AccessLevel,
		arg.Confidentiality,
		arg.IpOwnership,
		arg.ExitPlan,
		arg.TermsConfirmed,
		arg.OpeningID,
		arg.ApplicantUserID,
	)
	var i TrialProposal
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.OpeningID,
		&i.ApplicantUserID,
		&i.Outcome,
		&i.Deliverable,
		&i.NonGoals,
		&i.StartDate,
		&i.EndDate,
		&i.WeeklyHours,
		&i.CheckInCadence,
		&i.AccessLevel,
		&i.Confidentiality,
		&i.IpOwnership,
		&i.ExitPlan,
		&i.TermsConfirmed,
		&i.ProposalStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SentAt,
		&i.DecidedAt,
	)
	return i, err
}
