// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trial_proposals.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getOwnTrialProposal = `-- name: GetOwnTrialProposal :one
SELECT
    proposal.id, proposal.application_id, proposal.opening_id,
    proposal.applicant_user_id, proposal.outcome, proposal.deliverable,
    proposal.non_goals, proposal.start_date, proposal.end_date,
    proposal.weekly_hours, proposal.check_in_cadence, proposal.access_level,
    proposal.confidentiality, proposal.ip_ownership, proposal.exit_plan,
    proposal.terms_confirmed, proposal.proposal_status,
    proposal.created_at, proposal.updated_at
FROM trial_proposals AS proposal
JOIN applications AS application ON application.id = proposal.application_id
WHERE proposal.opening_id = $1
  AND proposal.applicant_user_id = $2
  AND application.status = 'accepted'
`

type GetOwnTrialProposalParams struct {
	OpeningID       string `db:"opening_id" json:"opening_id"`
	ApplicantUserID int64  `db:"applicant_user_id" json:"applicant_user_id"`
}

func (q *Queries) GetOwnTrialProposal(ctx context.Context, arg GetOwnTrialProposalParams) (TrialProposal, error) {
	row := q.db.QueryRow(ctx, getOwnTrialProposal, arg.OpeningID, arg.ApplicantUserID)
	var i TrialProposal
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.OpeningID,
		&i.ApplicantUserID,
		&i.Outcome,
		&i.Deliverable,
		&i.NonGoals,
		&i.StartDate,
		&i.EndDate,
		&i.WeeklyHours,
		&i.CheckInCadence,
		&i.AccessLevel,
		&i.Confidentiality,
		&i.IpOwnership,
		&i.ExitPlan,
		&i.TermsConfirmed,
		&i.ProposalStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertOwnTrialProposalDraft = `-- name: UpsertOwnTrialProposalDraft :one
INSERT INTO trial_proposals (
    id, application_id, opening_id, applicant_user_id, outcome, deliverable,
    non_goals, start_date, end_date, weekly_hours, check_in_cadence,
    access_level, confidentiality, ip_ownership, exit_plan, terms_confirmed
)
SELECT
    $1, application.id, application.opening_id,
    application.applicant_user_id, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11, $12,
    $13
FROM applications AS application
WHERE application.opening_id = $14
  AND application.applicant_user_id = $15
  AND application.status = 'accepted'
ON CONFLICT (application_id) DO UPDATE SET
    outcome = EXCLUDED.outcome,
    deliverable = EXCLUDED.deliverable,
    non_goals = EXCLUDED.non_goals,
    start_date = EXCLUDED.start_date,
    end_date = EXCLUDED.end_date,
    weekly_hours = EXCLUDED.weekly_hours,
    check_in_cadence = EXCLUDED.check_in_cadence,
    access_level = EXCLUDED.access_level,
    confidentiality = EXCLUDED.confidentiality,
    ip_ownership = EXCLUDED.ip_ownership,
    exit_plan = EXCLUDED.exit_plan,
    terms_confirmed = EXCLUDED.terms_confirmed,
    updated_at = now()
WHERE trial_proposals.proposal_status = 'draft'
RETURNING
    id, application_id, opening_id, applicant_user_id, outcome, deliverable,
    non_goals, start_date, end_date, weekly_hours, check_in_cadence,
    access_level, confidentiality, ip_ownership, exit_plan, terms_confirmed,
    proposal_status, created_at, updated_at
`

type UpsertOwnTrialProposalDraftParams struct {
	ID              string      `db:"id" json:"id"`
	Outcome         string      `db:"outcome" json:"outcome"`
	Deliverable     string      `db:"deliverable" json:"deliverable"`
	NonGoals        string      `db:"non_goals" json:"non_goals"`
	StartDate       pgtype.Date `db:"start_date" json:"start_date"`
	EndDate         pgtype.Date `db:"end_date" json:"end_date"`
	WeeklyHours     int32       `db:"weekly_hours" json:"weekly_hours"`
	CheckInCadence  string      `db:"check_in_cadence" json:"check_in_cadence"`
	AccessLevel     string      `db:"access_level" json:"access_level"`
	Confidentiality string      `db:"confidentiality" json:"confidentiality"`
	IpOwnership     string      `db:"ip_ownership" json:"ip_ownership"`
	ExitPlan        string      `db:"exit_plan" json:"exit_plan"`
	TermsConfirmed  bool        `db:"terms_confirmed" json:"terms_confirmed"`
	OpeningID       string      `db:"opening_id" json:"opening_id"`
	ApplicantUserID int64       `db:"applicant_user_id" json:"applicant_user_id"`
}

func (q *Queries) UpsertOwnTrialProposalDraft(ctx context.Context, arg UpsertOwnTrialProposalDraftParams) (TrialProposal, error) {
	row := q.db.QueryRow(ctx, upsertOwnTrialProposalDraft,
		arg.ID,
		arg.Outcome,
		arg.Deliverable,
		arg.NonGoals,
		arg.StartDate,
		arg.EndDate,
		arg.WeeklyHours,
		arg.CheckInCadence,
		arg.AccessLevel,
		arg.Confidentiality,
		arg.IpOwnership,
		arg.ExitPlan,
		arg.TermsConfirmed,
		arg.OpeningID,
		arg.ApplicantUserID,
	)
	var i TrialProposal
	err := row.Scan(
		&i.ID,
		&i.ApplicationID,
		&i.OpeningID,
		&i.ApplicantUserID,
		&i.Outcome,
		&i.Deliverable,
		&i.NonGoals,
		&i.StartDate,
		&i.EndDate,
		&i.WeeklyHours,
		&i.CheckInCadence,
		&i.AccessLevel,
		&i.Confidentiality,
		&i.IpOwnership,
		&i.ExitPlan,
		&i.TermsConfirmed,
		&i.ProposalStatus,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
